### ISSUE TITLE
setting up two gunicorn instances

### ISSUE THREAD

**Issue by Six-wars** [benoitc/gunicorn#1462] opened 2017-02-14 08:12 UTC
Got gunicorn setup like so

```
[Unit]
Description=gunicorn daemon
After=network.target

[Service]
User=ubuntu
Group=www-data

WorkingDirectory=/home/ubuntu/webapps/kenyabuzz


ExecStart=/home/ubuntu/webapps/djangoenv/bin/gunicorn --workers 3 --bind unix:/home/ubuntu/webapps/kenyabuzz/kb.sock kb.wsgi:application

[Install]
WantedBy=multi-user.target
```

I can edit the working directory to `uganda_buzz` and `unix:/home/ubuntu/webapps/uganda_buzz/ug.sock kb.wsgi:application` and run the other site however can't figure out how to run both of them from this setting.

**Comment by berkerpeksag** [comment] 2017-02-14 10:08
This is a duplicate of #1461, isn't it?

**Closed by berkerpeksag** 2017-02-14 10:08 UTC

**Comment by Six-wars** [comment] 2017-02-14 11:09
Yes it's a duplicate simplifying the issue.
