### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING problem

### ISSUE THREAD

**Issue by neomagic** [benoitc/gunicorn#1233] opened 2016-03-23 06:36 UTC
Hello:

I wrote a simple "Server Sent Event" code in Flask , it work fine use the Flask app.run() with the threaded option. But when I use gunicorn start the app , I found that in the chrome console it will raise up "net::ERR_INCOMPLETE_CHUNKED_ENCODING" error message , I add 'Cache-Control':'no-cache' in the Flask respone header but it still appear the "net::ERR_INCOMPLETE_CHUNKED_ENCODING" error message.

I google it many times but still not found the right answer to fix that problem , hopes for somebody help . thx

**Comment by benoitc** [comment] 2016-03-23 09:30
Can you provide a way to reproduce the issue? Reading from it it seems you're not sending correct a correct response from flask. Any code around that could help to test?

**Comment by jamadden** [comment] 2016-03-23 11:50
FWIW, gevent has had [one report](https://github.com/gevent/gevent/issues/778) of possible data truncation talking to Chrome under Python 3. There's not much information in that report yet, but I wonder what worker and Python version @neomagic is using.

**Comment by benoitc** [comment] 2016-03-25 09:57
@neomagic ping :) can you provide an HTTP trace or example to help to reproduce the issue?

**Comment by benoitc** [comment] 2016-05-02 11:45
no answer since and not reproduced internally. closing the issue. Feel free to open a new one if the problem still persists.

**Closed by benoitc** 2016-05-02 11:45 UTC
Labels: Feedback Requested, Investigation
