### ISSUE TITLE
19.3.0 install error!

### ISSUE THREAD

**Issue by pikeas** [benoitc/gunicorn#1017] opened 2015-04-28 23:16 UTC
```python
root@05c1274ac87d:/app# pip install gunicorn
Downloading/unpacking gunicorn
  Downloading gunicorn-19.3.0-py2.py3-none-any.whl (110kB): 110kB downloaded
Installing collected packages: gunicorn
Compiling /tmp/pip-build-w_bHnJ/gunicorn/gunicorn/workers/_gaiohttp.py ...
  File "/tmp/pip-build-w_bHnJ/gunicorn/gunicorn/workers/_gaiohttp.py", line 68
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax
Successfully installed gunicorn
```

This is Python 2.7.9 running on Ubuntu, so I'm not sure why it's trying to use a Python3 `yield from`?

**Comment by tilgovi** [comment] 2015-04-28 23:52
This is a duplicate issue that has been filed several times. It is harmless (install completes successfully) and it is fixed by upgrading pip.

**Closed by tilgovi** 2015-04-28 23:52 UTC

**Comment by pikeas** [comment] 2015-04-28 23:53
@tilgovi I'm running the latest version of pip (6.1.1), so that is not the cause. Reopen?

**Comment by tilgovi** [comment] 2015-04-28 23:57
Are you sure that's the version of pip being used in the environment where you're install gunicorn? This issue is well known, @berkerpeksag submitted the patch upstream to pip if I recall correctly, it has been filed several times with the same symptom and been reported to be fixed by upgrading pip. I have just tested myself and cannot reproduce on that version of pip.

**Comment by pikeas** [comment] 2015-04-29 00:15
@tilgovi User error on my side, Pip was *supposed* to be upgraded on my side, but was actually an outdated version.

Still worth adding to the FAQ and/or GH page if lots of people are opening issues about it.

**Comment by tilgovi** [comment] 2015-04-29 00:28
It'll solve itself in time as the default versions get upgraded. A simple search for the output message should reveal the several times we've closed the issue and the cause. Finding the FAQ is most likely no easier.

Glad you're on your way. Cheers.
