### ISSUE TITLE
Gunicorn default error logging date format is not standard ISO8601

### ISSUE THREAD

**Issue by kozmaz87** [benoitc/gunicorn#1771] opened 2018-05-03 12:21 UTC
https://github.com/benoitc/gunicorn/blob/e73ca252f7e1d0286998a0ae4254164291020a0c/gunicorn/glogging.py#L88

The motivation for this issue is the following grok statement in logstash:

`
grok {
      match => { "message" => "\[(?<gunicorn.time>%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})? %{ISO8601_TIMEZONE})\] \[%{NUMBER:[gunicorn][worker_id]}\] \[%{LOGLEVEL:[gunicorn][level]}\] %{GREEDYDATA:[gunicorn][message]}" }
      remove_field => "message"
    }
`

Had the date format included **no space between the time and the time zone** the following statement would have cut it:

`
grok {
      match => { "message" => "\[%{TIMESTAMP_ISO8601:[gunicorn][time]}\] \[%{NUMBER:[gunicorn][worker_id]}\] \[%{LOGLEVEL:[gunicorn][level]}\] %{GREEDYDATA:[gunicorn][message]}" }
      remove_field => "message"
    }
`

I would argue that a standard date format would be better suited for a default configuration. I think adding an extra space there adds no value but creates problems instead. Either having to replace the whole default logconfig, which is excessive, or having to write custom expressions in log parsers to cater for it.

**Comment by tilgovi** [comment] 2018-05-03 20:11
Oh, my apologies. My response is about the access log format. This report is about the error log format.

**Comment by tilgovi** [comment] 2018-05-03 20:18
Looks like you could use `%{DATESTAMP} %{ISO8601_TIMEZONE}`

**Comment by benoitc** [comment] 2018-07-04 07:48
@tilgovi so is this something wanted?

**Comment by kozmaz87** [comment] 2018-07-16 18:13
A possible compromise could be a switch and deprecation. You can start phasing out the odd(however so slightly) date format that is not following standards and provide the user with a switch to a fixed log line format. I know that I can override the logger via python but since gunicorn comes with its competing settings baked in it would not be my favourite choice :D I am not an OCD person but cooking up a grok query is a modern type of torture especially when the difference you are accounting for is one space :D And then it is up to the developer to maintain that longer than necessary match should anything change. It is not the end of the world if one has to but we keep fixing bugs even if people rely on the buggy software... That is what I think... not sure if the question was pointed at me...

**Comment by tilgovi** [comment] 2018-07-16 20:10
We could look at changing the default for R20.

**Comment by benoitc** [comment] 2018-07-17 09:53
This format is pretty common actually. The rfc 3339 have an ote about it 👍 

> NOTE: ISO 8601 defines date and time separated by "T".  Applications using this syntax may choose, for the sake of   readability, to specify a full-date and full-time separated by    (say) a space character.

The error log is also printed on the command line and should be read by a human and I would like to keep it that way. Is there any issue with the timezone format ?

**Comment by kozmaz87** [comment] 2018-08-13 17:34
Ok so that does mean that grok in logstash is preloaded with a strict pattern rather than the lenient one. I have worked with standards people before at the BBC/EBU and I remember this kind of terrible wording. For readability "(say) a space character" This is not implementable.... what is that character? Of course you can allow any character at this point and that is not OK. So the guys at Logstash implemented this the following way to be either T or space 

  TIMESTAMP_ISO8601 %{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?

Furthermore THIS IS NOT WHAT THE ISSUE WAS ABOUT. What the issue was about is the timezone suffix having a space that the standard DOES NOT ALLOW.

**Comment by tilgovi** [comment] 2018-08-13 17:54
That's helpful, @kozmaz87. Thanks for digging into the spec.

**Comment by kozmaz87** [comment] 2018-08-13 17:59
But since we are here I would love to also point to the access log format, which is even worse. I did not even manage to find in the code any place where it is coming from... It is constructed from some pretty obscure configuration mechanism. assigned from somewhere else. I did not checkout the code to investigate but it does produce this output:

`
127.0.0.1 - - [13/Aug/2018:15:03:26 +0000] "GET /debug/sms HTTP/1.1" 400 74 "-" "python-requests/2.18.4"
`

Looking at the gunicorn docs we learn that the 2nd part of this log is a '-' for whatever reason... the 3rd is supposed to be the user, which is also evaluating to '-' not sure why and then comes this lovely date format where the hour is married to the year by a ':' and of course the favourite space separated timezone suffix again. But after digging around I found that this is how nginx logs it so I assume this is where this space separated timezone thing is originating from by trying to mimic the nginx access logs. HAProxy does use this as well except it does not put a timezone suffix on... 

Logging is crazy... Someone bring me a bucket of icy water :)

**Comment by tilgovi** [comment] 2018-08-13 18:04
The access log format is definitely "common": https://en.wikipedia.org/wiki/Common_Log_Format

**Comment by tilgovi** [comment] 2018-08-13 18:07
We add referrer and user agent to the end, though. Refer to the `--access-logformat` flag: http://docs.gunicorn.org/en/latest/settings.html#access-log-format

**Comment by kozmaz87** [comment] 2018-08-13 18:15
I realise that. I just find it funny that the 2nd item is a '-' :D It feels like whoever implemented it had had it with this and just put in a '-'

**Comment by benoitc** [comment] 2019-01-11 04:09
i would keep the current log format. imo common format is good and I am not aware about any change in servers upstream. thoughts? cc @tilgovi

**Comment by benoitc** [comment] 2019-01-24 15:41
bump @tilgovi also @berkerpeksag

**Comment by benoitc** [comment] 2019-01-24 21:11
closing the issue as won't fix. As said @tilgovi we are following the [common log format](
https://en.wikipedia.org/wiki/Common_Log_Forma)t

**Comment by tilgovi** [comment] 2019-01-24 21:21
I think we could keep this open. We are not using the common log format for the error log. The common log format is an access log format and we use it there.

**Comment by tilgovi** [comment] 2019-01-25 19:50
I understand the issue better now and think we should re-open.

Here's example output from Gunicorn with default settings:

> [2019-01-25 11:44:34 -0800] [22794] [INFO] Starting gunicorn 19.9.0
> [2019-01-25 11:44:34 -0800] [22794] [INFO] Listening at: http://127.0.0.1:8000 (22794)
> [2019-01-25 11:44:34 -0800] [22794] [INFO] Using worker: sync
> [2019-01-25 11:44:34 -0800] [22797] [INFO] Booting worker with pid: 22797
> [2019-01-25 11:44:36 -0800] [22797] [INFO] 127.0.0.1 - - [25/Jan/2019:11:44:36 -0800] "GET / HTTP/1.1" 200 14 "-" "curl/7.54.0"

The issue is not about parsing the common log format of the access log, it's about parsing the _entire log line_.

Gunicorn outputs a timestamp, pid, and level at the start of the log line. The access log lines _also_ have a message in common log format with its own timestamp.

Notice how the timestamps are not in the same format. The original request for this issue was to have the timestamp at the start of the log line have no space _just like the common log format_.

That would look like this:
> [25/Jan/2019:11:44:34 -0800] [22794] [INFO] Starting gunicorn 19.9.0
> [25/Jan/2019:11:44:34 -0800] [22794] [INFO] Listening at: http://127.0.0.1:8000 (22794)
> [25/Jan/2019:11:44:34 -0800] [22794] [INFO] Using worker: sync
> [25/Jan/2019:11:44:34 -0800] [22797] [INFO] Booting worker with pid: 22797
> [25/Jan/2019:11:44:36 -0800] [22797] [INFO] 127.0.0.1 - - [25/Jan/2019:11:44:36 -0800] "GET / HTTP/1.1" 200 14 "-" "curl/7.54.0"

**Comment by tilgovi** [comment] 2019-01-25 19:59
I think the answer is probably not, because the common log format is not as international (it has a short month name).

However, we could change the timestamp at the start of each log line to be an ISO8601 timestamp.

https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations

The space between date and time is actually allowed in place of a T character, but a space between the time and the zone offset is not.

Here are valid ISO8601 formats we could have:

- `[2019-01-25T11:44:34-0800]`
- `[2019-01-25 11:44:34-0800]`

I would very much worry about breaking deployed systems, though.

**Comment by benoitc** [comment] 2019-01-25 20:05
well parsing/reformatting logs can easily be handled tools like logstash, so I'm not sure it's an issue. I would keep it that way for now.

If people want a different format for access logs maybe we can add a specific identifier for it? That way we wouldn't break the format. Error logs are however an issue since we don't provide a way to format them. In such case maybe an environment variable would do it?

**Comment by tilgovi** [comment] 2019-01-25 20:14
I don't think the access log format should change. It is common log format right now and we have the `--access-log-format` setting.

The access log format only formats the _message_ of the access log that gets passed to the handler. The handler then has its own formatter.

Our default formatter for the stream handlers on stdout and stderr put a timestamp on the beginning. That means that with the default configuration the access log has _two_ timestamps: one at the beginning and one in the message.

Changing the formatter for the handler requires using one of the `--logconfig` options (file or dict).

We should consider having an ISO8601 timestamp in the default formatter.

**Comment by tilgovi** [comment] 2019-01-25 20:15
> parsing/reformatting logs can easily be handled tools like logstash

Yes, but it's very convenient when those tools can parse the timestamp with built-in patterns so the user doesn't have to write a regexp. The original issue was opened because grok has a built-in pattern for ISO8601 timestamps.

**Comment by benoitc** [comment] 2019-01-25 21:13
@tilgovi I don't want to break the compatibility. Also NGINX does offer the possibility to set the time either using ISO8601 format or Common Log Format : 

```
$time_iso8601
local time in the ISO 8601 standard format
$time_local
local time in the Common Log Format
```
https://nginx.org/en/docs/http/ngx_http_log_module.html

I would do the same since it doesn't break the legacy.  Btw shouldn't we just display the access log line to the output? It seems we shouldn't not have the first header with the PID. Thoughts?

**Comment by benoitc** [comment] 2019-01-25 21:20
about making it part of the default formatter i'm worried it breaks some tool around. What about having a custom environment variable `TIME_ISO8601=true` to force it?

**Comment by tilgovi** [comment] 2019-01-25 22:13
> I don't want to break the compatibility.

I don't either. I only wanted to re-open the ticket because I think we closed it for the wrong reason. We both responded as though the issue was to change from common log format. The issue is the timestamp in the default formatter, not the format of the access log message. I'm glad we can discuss it more, but the answer maybe is to still do nothing.

> Btw shouldn't we just display the access log line to the output? It seems we shouldn't not have the first header with the PID. Thoughts?

Possible. I'm not sure.

> What about having a custom environment variable

Maybe okay. The user can always control the log completely by using the advanced logging configuration. We try to make some settings simple for the CLI, like `--log-level`, so users do not have to use configuration files. Maybe we could add `--log-date-format`? It could even recognize symbolic strings like `iso8601`. This setting would be for users that don't want to use `--log-config` or `log_config_dict`.

**Comment by tilgovi** [comment] 2019-01-27 23:08
Just to be sure, this would be the proposed diff if we just changed the default:

``` diff
diff --git a/gunicorn/glogging.py b/gunicorn/glogging.py
index 56cc5bd..0735e58 100644
--- a/gunicorn/glogging.py
+++ b/gunicorn/glogging.py
@@ -80,7 +80,7 @@ CONFIG_DEFAULTS = dict(
         formatters={
             "generic": {
                 "format": "%(asctime)s [%(process)d] [%(levelname)s] %(message)s",
-                "datefmt": "[%Y-%m-%d %H:%M:%S %z]",
+                "datefmt": "[%Y-%m-%d %H:%M:%S%z]",
                 "class": "logging.Formatter"
             }
         }
@@ -175,7 +175,7 @@ class Logger(object):
     loglevel = logging.INFO
 
     error_fmt = r"%(asctime)s [%(process)d] [%(levelname)s] %(message)s"
-    datefmt = r"[%Y-%m-%d %H:%M:%S %z]"
+    datefmt = r"[%Y-%m-%d %H:%M:%S%z]"
 
     access_fmt = "%(message)s"
     syslog_fmt = "[%(process)d] %(message)s"
```

**Comment by tilgovi** [comment] 2019-01-27 23:11
I think an option to use an ISO8601 datetime in the access log tokens is interested, but it's separate from what motivated this issue.

**Comment by tilgovi** [comment] 2019-01-27 23:15
I don't feel strongly about this, by the way. 😄 I just want to represent the issue accurately.

**Comment by benoitc** [comment] 2019-09-27 18:29
we probably need to think a little bit more about it. I am postponing it to 20.1 to let us some times.

**Comment by cbueche** [comment] 2019-10-30 13:29
Dear devels,
I'm facing a request loss issue (has nothing to do with Gunicorn). I would need to be able to have the precise timestamp including the microseconds, as in this example from one of our Apache servers : `2019-10-30 14:27:16.960421`. It would be a cool enhancement, thx for considering it.

**Comment by ianhundere** [comment] 2020-07-07 18:47
Any hope if the flag, `log-date-format iso8601`, will be available in the next vers of gunicorn?

**Comment by stefansjs** [comment] 2021-12-16 19:58
I've been digging in to logging in gunicorn recently. It seems to me that access_log_format (aka --access-logformat) is not sufficient. It seems like datefmt is a missing feature. Am I missing the configuration parameter? It's definitely not documented here https://docs.gunicorn.org/en/stable/settings.html#access-log-format. 

There are lots of idiosyncratic configurations here. I also noticed a few rather strange things, like process ID is surrounded with <> in the `'%(p)s'` format, whereas the python logger represents it with `'%(process)d'`, as in a real integer. Would it be possible to (1) get all the standard python logging variables available in the log format, and (2) provide more control over formatting those individual components? I could either imagine datefmt-esque configuration parameters for each parameter, or new parameters with the true underlying type so that the string formatter can do what it pleases (e.g. `<%(process)05d>`)

It seems like exposing datefmt as a configuration parameter for the access and error logs feels pretty important.

**Comment by benoitc** [comment] 2024-08-06 13:49
no activity since awhile. closing feel free to create a new ticket if needed.

**Closed by benoitc** 2024-08-06 13:49 UTC
Labels: Improvement, Discussion, Feature/Logging

**Comment by ddelange** [comment] 2024-10-30 13:26
What was the consensus here? Apart from space before timezone, how can we get ISO8601 timestamps in the gunicorn access logs? Is there a way to use locales (env vars) and/or `--access-logformat`?

**Comment by zhermin** [comment] 2025-01-19 19:53
Found a quick and dirty way:

```python
import time
from gunicorn.glogging import Logger

ISO8601_DATE_FORMAT = r"%Y-%m-%dT%H:%M:%S%z"

class GunicornLogger(Logger):
    def now(self):
        return time.strftime(ISO8601_DATE_FORMAT)
```

```bash
> gunicorn --logger-class my.path.to.GunicornLogger --access-logfile=- app:app

127.0.0.1 - - 2025-01-20T00:00:00+0000 "GET / HTTP/1.1" 200 5 "-" "curl/8.7.1"
```

Works because [`gunicorn.glogging.py`'s timestamp log formatting atom `%(t)s`](https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L300) calls [`self.now()`](https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L366-L368), which is used in the [`--access-logformat`](https://docs.gunicorn.org/en/stable/settings.html#access-log-format). 

---

If you also want to do it for `error_log` it's somehow easier because it can take in any `Formatter`: 

```python
class GunicornLogger(Logger):
    def setup(self, cfg):
        super().setup(cfg)
        self._set_handler(
            self.error_log,
            cfg.errorlog,
            logging.Formatter(self.error_fmt, ISO8601_DATE_FORMAT),
        )
```
