### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT on docker container (mozilla syncserver)

### ISSUE THREAD

**Issue by dojo90** [benoitc/gunicorn#1977] opened 2019-02-05 07:31 UTC
When using my mozilla syncserver docker container (https://github.com/dojo90/synology-docker-mozilla-syncserver) with gunicorn included, I always get this errors:

```
[2019-02-05 05:46:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:180)

[2019-02-05 05:51:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:181)

[2019-02-05 05:56:43 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:182)

[2019-02-05 07:01:43 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:183)

[2019-02-05 07:06:44 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:179)

[2019-02-05 07:11:44 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:184)

[2019-02-05 07:16:45 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:186)

[2019-02-05 07:21:45 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:185)

[2019-02-05 07:26:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:187)
```

I have already increased timeout and workers:

```
[server:main]
use = egg:gunicorn
host = 0.0.0.0
port = 5000
workers = 3
timeout = 300
keyfile = /etc/ssl/certs/privatekey.key
certfile = /etc/ssl/certs/certificate.crt

forwarded_allow_ips = *
#debug = True
#accesslog = -
errorlog = -
loglevel = warning
```

**Comment by dojo90** [comment] 2019-02-07 10:52
I run it on a Synology ds918+. I don't think that there is a loadbalancer or anything. Got also really "heavy" dockers like "plex" with 2GB Ram usage running without any problems.

**Comment by dojo90** [comment] 2019-02-13 08:10
I'm still investigating it. But since I made this post, I didn't get this error anymore. So I will post an update if it comes back! I had this error for about 1 year and know it is gone.. 🤔

**Comment by dojo90** [comment] 2019-02-15 07:45
```
[2019-02-15 07:28:19 +0000] [11] [DEBUG] GET /token/1.0/sync/1.5
[2019-02-15 07:28:19 +0000] [11] [DEBUG] GET /storage/1.5/1/info/collections
[2019-02-15 07:28:20 +0000] [12] [DEBUG] GET /storage/1.5/1/info/configuration
[2019-02-15 07:28:20 +0000] [12] [DEBUG] GET /storage/1.5/1/storage/clients
[2019-02-15 07:28:21 +0000] [12] [DEBUG] POST /storage/1.5/1/storage/tabs
[2019-02-15 07:28:22 +0000] [12] [DEBUG] POST /storage/1.5/1/storage/forms
[2019-02-15 07:28:23 +0000] [11] [DEBUG] POST /storage/1.5/1/storage/history
[2019-02-15 07:28:50 +0000] [13] [DEBUG] Error processing SSL request.
[2019-02-15 07:28:50 +0000] [13] [DEBUG] Invalid request from ip=172.17.0.1: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1941)
[2019-02-15 07:33:50 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:13)
[2019-02-15 07:33:50 +0000] [13] [DEBUG] Failed to send error message.
[2019-02-15 07:33:50 +0000] [13] [INFO] Worker exiting (pid: 13)
[2019-02-15 07:33:50 +0000] [12] [DEBUG] Error processing SSL request.
[2019-02-15 07:33:50 +0000] [12] [DEBUG] Invalid request from ip=172.17.0.1: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1941)
[2019-02-15 07:33:51 +0000] [14] [INFO] Booting worker with pid: 14
[2019-02-15 07:38:14 +0000] [12] [DEBUG] Failed to send error message.
```

Ok I could reproduce the problem.

I had one client, which was not using `https` endpoint. After changing `http` to `https` everything is fine! 
😃👍

**Comment by tilgovi** [comment] 2019-02-15 17:54
Thanks for that @dojo90! Very helpful! I suggest we leave the issue open. I'd like to investigate whether there's something defensive we could do to prevent the timeouts in this scenario.

To clarify, this was happening when a client attempted an `http` connection to an `https`-bound Gunicorn worker?

**Comment by dojo90** [comment] 2019-02-18 07:47
> To clarify, this was happening when a client attempted an `http` connection to an `https`-bound Gunicorn worker?

Exactly!

1. Client wants to connect to `http` -> error -> timeout
2. Client was to connect to `http` -> error -> changed client to `https` -> works without a timeout error message

**Comment by javabrett** [comment] 2019-02-22 03:10
This is a duplicate of #1929.  See my comment https://github.com/benoitc/gunicorn/issues/1929#issuecomment-443573007 .

There is a general worker stall/timeout issue when the first EOL is never sent by the client.  This exactly occurs when the first line data is a SSL/TLS handshake, but it is being made on a plain HTTP port.

**Comment by javabrett** [comment] 2020-01-12 00:52
Closing as what seems to be a pretty clear duplicate of #1929 - watchers please comment here if that doesn't look right.

**Closed by javabrett** 2020-01-12 00:52 UTC
