### ISSUE TITLE
When requests.get a timeout page, my program is 502 error.

### ISSUE THREAD

**Issue by fortunearterial** [benoitc/gunicorn#1639] opened 2017-11-07 06:05 UTC
Please help me solve this problem. 
I'm using requests.get(url) to get images in the page, by testing the url http://yugiohmonstrosdeduelo.blogspot.com/, the system down and return 502 error, even there isn't any log for me.

my server is nginx + gunicron + python3 + requests.

**Comment by benoitc** [comment] 2017-11-07 07:42
any log to share?

**Comment by fortunearterial** [comment] 2017-11-10 02:19
I'm sorry, but there isn't any log in nginx error.log file and my gunicorn log file.
good news, my amazon ec2 server doesn't have this problem. but my linode server has.

there are any body have the same problem? please tell me how to check it! my mind is gone away.

**Comment by tilgovi** [comment] 2017-11-10 06:21
Could this be the same as #1507?

**Comment by hingston** [comment] 2017-12-01 20:30
I'm not sure I quite understand the problem here but it could possibly be related to #1655

**Comment by benoitc** [comment] 2019-11-22 21:42
closing issue, duplicate of #1507

**Closed by benoitc** 2019-11-22 21:42 UTC
Labels: Feedback Requested
