### ISSUE TITLE
"OSError: [Errno 11] Resource temporarily unavailable" raised when use gunicorn(gevent) with gitpython

### ISSUE THREAD

**Issue by Winiex** [benoitc/gunicorn#1036] opened 2015-05-21 07:10 UTC
Hi,

I use gunicorn with gevent to serve a service that automatically push new commits to git remote repo, with the git stuff implemented with GitPython module.

But when I start up the process using this command below:

>gunicorn -w 1 -k gevent -b 0.0.0.0:10001 --max-requests 2000 --log-level debug --name flask "app:create_app()"

When a request comes in, this error is raised:

>Exception in thread Thread-3:
>Traceback (most recent call last):
>  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>  self.run()
>  File "/usr/lib/python2.7/threading.py", line 763, in run
>    self.__target(*self.__args, **self.__kwargs)
>  File "/home/deploy/.virtualenvs/flask/local/lib/python2.7/site-packages/git/cmd.py", line 196, in <lambda>
>    t = threading.Thread(target=lambda: deplete_buffer(fno, handler, buf_list, wg))
>  File "/home/deploy/.virtualenvs/flask/local/lib/python2.7/site-packages/git/cmd.py", line 129, in deplete_buffer
>    line_count = dispatch_lines(fno, handler, buf_list)
>  File "/home/deploy/.virtualenvs/flask/local/lib/python2.7/site-packages/git/cmd.py", line 120, in dispatch_lines
>    for line in read_lines_from_fno(fno, buf_list):
>  File "/home/deploy/.virtualenvs/flask/local/lib/python2.7/site-packages/git/cmd.py", line 95, in read_lines_from_fno
>    buf = os.read(fno, mmap.PAGESIZE)
>OSError: [Errno 11] Resource temporarily unavailable

I guess this problem is caused by gevent, so I just remove the gevent part from the command:

>gunicorn -w 1 -b 0.0.0.0:10001 --max-requests 2000 --log-level debug --name flask "app:create_app()"

This time, everything works pretty fine.

Here is my server info:

>Linux app 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I use flask as the web framework, but I think it's not its problem.

**Comment by tilgovi** [comment] 2015-05-21 20:23
Gunicorn version? Have you read through these issues? https://github.com/benoitc/gunicorn/issues?q=is%3Aissue+resource+unavailable+is%3Aclosed

Anything else you can tell us about your environment that might help? A simple application that you can use to reproduce it?

**Comment by benoitc** [comment] 2015-05-25 06:27
The error is probably coming fro, the MMAP buffer reqd: `buf = os.read(fno, mmap.PAGESIZE)` . AT that point you probably need to add a trampoline so you can wait until the MMAP is readable.

**Comment by benoitc** [comment] 2016-10-16 15:59
no more activity on that issue and the problem is outside of gunicorn. closing the issue, feel free to reopen it if you think it needs more actions.

**Closed by benoitc** 2016-10-16 15:59 UTC
