### ISSUE TITLE
Allow for a way to determine the current worker ID

### ISSUE THREAD

**Issue by hynek** [benoitc/gunicorn#1352] opened 2016-09-20 14:04 UTC
If I run an application in multi-process mode, it would be very useful for introspection to be able to determine which worker I actually am.  And by that I don’t mean the pid but an integer that goes from 1 to `--workers=WORKERS` (if a worker dies, the new one gets the worker id of it, not a new one).

An example for that is uwsgi’s `uwsgi.worker_id()` (that starts at 0 FWIW).

**Comment by hynek** [comment] 2016-09-21 16:33
For anyone who’s also interested in this kind of feature:  I managed to work around using callbacks: https://gist.github.com/hynek/ba655c8756924a5febc5285c712a7946

An official and elegant way would still be appreciated. :)

**Comment by tilgovi** [comment] 2016-09-21 21:01
This looks like a duplicate of #1118, which was closed with #1278 as a proposed next steps.

@hynek does that match what you see? Can we consolidate these issues?

**Comment by hynek** [comment] 2016-09-22 11:20
I‘m not 100% sure from reading the tickets.   Will #1278 make it possible to get a stable worker id but only so many IDs as there’s max workers (i.e server.cfg.worker + everything you’ve `TTIN`’ed)?

**Comment by GMLudo** [comment] 2016-09-26 18:46
Hi @hynek,

Your gist is exactly what I'm looking for: With that, it's possible to specialize a worker when you have tasks must be executed only one time in the workers cluster, like a scheduler or to detect data corruptions. For now, I'm using cron or at to launch a curl command to wake-up a random worker via Gunicorn.

After the read of #1278, I'm agree with @hynek, it isn't exactly that: If I understand correctly the API proposed by @benoitc, you must first attribute a name before to use. In my case, if I have several workers that started as the same time, like at gunicorn startup, I might have a race condition between two workers that its have taken the same name at the same time.

For me, an integration of @hynek 's idea in the Gunicorn will be very useful, at least to me.

Have a nice day.

**Comment by tilgovi** [comment] 2016-09-26 19:34
I hesitate to endorse @hynek's approach for the same reasons that were discussed in the code comments on #1118.

Workers already have two unique IDs — pid and age, where age is the ordinal position of the worker in the total history of workers started by the arbiter. As this evidently seems insufficient for some desired use cases (or we wouldn't have this issue), let me lay out a few desirable constraints and then the ways that they are in conflict:

Constraint A: Worker IDs should be in the range `[0,n)` where `n` is the number of workers
Constraint B: Workers should never have the same ID

We have these issues to address with our proposals:

- Given that the `reload` command spawns `n` new workers before the old workers are killed, the new workers must have higher IDs due to Constraint B, but after the old workers exit Constraint A is violated.

- Reload and `TTOU` handling rely on the implementation of the arbiter run loop to terminate the oldest `m - n` workers where `m` is the count of workers and `n` is the desired count. We would need to change this implementation or Constraint A will be violated after `TTOU`.

I'll refrain from making suggestions so as not to unintentionally constrain the creativity of solutions others might propose.

**Comment by hynek** [comment] 2016-09-26 19:54
Yes A and B are mutually exclusive due to the way `HUP` works.  I guess everyone has to decide which is more important to them.  I’ve decided for myself that I can live with short-time violations of B because I really just need it for metrics.

**Comment by tilgovi** [comment] 2016-10-01 01:37
We could make `TTOU` kill the highest numbered worker and have reload start numbering with 0. I think this would mostly satisfy both constraints. If it's okay to have some periods where workers with duplicate ids exist, this would be a solution.

**Comment by GMLudo** [comment] 2016-10-01 20:00
Thank you a lot guys for your remarks: In fact, in my use case, it's a no-go: I must be sure that only one worker does this job.
In fact, the easiest way, is to have two daemons, where one daemon has only one worker.
While I'm thinking, it might be a parameter I'll pass to my daemon and I create two services: With that, I can reuse easily source code and I can control easily the two differents roles via the service.
The other way might be to define different class of workers to avoid to have an arbiter by role, but certainly complex to implement for a ROI almost null.

**Comment by tilgovi** [comment] 2016-10-01 20:03
Thank you everyone for the discussion.

I think at this point I will close the issue. It's here as documentation with links to the workarounds posted, but it's not clear at this time what the best course of action for Gunicorn is.

Everyone should feel free to open a new issue with a concrete proposal that addresses and explains a particular need and acknowledges the constraints and conflicting goals of the different possible implementations. Until then, I don't see what action we can take.

**Closed by tilgovi** 2016-10-01 20:03 UTC
