### ISSUE TITLE
cpu spike on terminal resize

### ISSUE THREAD

**Issue by w-p** [benoitc/gunicorn#1269] opened 2016-05-17 20:30 UTC
I'm not sure if what follows is an issue with gunicorn, Terminator, both, or neither.  I run Debian (8), I use Terminator to split up my shells, I run web apps with gunicorn.  Pretty straightforward.

While resizing any of the terminals adjacent to that which is running gunicorn, for every movement event tracked, the two lines below are printed and multiple cores of my cpu (i7 4712) are pegged at 100% (or close), until I kill off gunicorn and start it up again.
```
[2016-05-17 16:09:55 -0400] [21121] [INFO] Handling signal: winch
[2016-05-17 16:09:55 -0400] [21121] [DEBUG] SIGWINCH ignored. Not daemonized
```
Clearly this is running in the foreground while debugging things.  This behavior is not present if the terminal size remains unchanged.  Not a big issue, just an annoyance.

**Comment by benoitc** [comment] 2016-05-18 09:37
@w-p only these 2 lines once or it appears more often?

**Comment by w-p** [comment] 2016-05-18 10:35
The lines are repeated for every row / col change (SIGWINCH) to the terminal. In other words, while dragging the resize handle of the terminal window, lines are output. When not resizing, the lines do not continue - but elevated CPU usage does.

**Comment by tilgovi** [comment] 2016-05-20 02:16
It would be really interesting to know if there is a commit that introduced that we can find via bisect. It's possible we're not clearing some state due to some kind of race or something.

**Comment by vlt** [comment] 2016-05-20 08:14
I experience the same reproducable behaviour.

I’m running Django 1.9.6 with Python 3.4.3 and gunicorn 19.5.0 in a virtualenv behind nginx on Ubuntu 14.04 (DigitalOcean).

As soon as I resize my “screen” terminal (by splitting, the `:resize` command, or just by re-attaching to the session from another terminal) the workers’s load goes up to `25 %CPU` each. Permanently. The system load avg approaches `n.00` (`n` being the number of workers).
After sending `SIGHUP` (booting new workers) evrything calms down.

**Comment by benoitc** [comment] 2016-05-20 09:13
I can reproduce it as well. Working on it :)

**Comment by benoitc** [comment] 2016-05-20 09:31
@tilgovi so b0c03332489c86c1d5dc0c8dbc37fa202a378f3e introduced the issue.

When you receive a SIGCHLD, it ` signal.set_wakeup_fd` continuously write on the pipe and always wake up the worker. Which triggers the CPU spike. Maybe an issue in Python 3.5 ? cc @berkerpeksag 

Anyway trying to find a proper fix.

**Comment by benoitc** [comment] 2016-05-20 09:42
@berkerpeksag actually nevermind. My bad I was not reading the signal bit written in the pipe. fixed now.

**Closed** 2016-05-20 09:41 UTC
Labels: Bug, Working On It

**Comment by dirkroorda** [comment] 2019-11-21 12:33
Still, when I resize the terminal in which I issued the gunicorn command, I get a lot of winch signals:

```
[2019-11-21 13:25:41 +0100] [28240] [INFO] Starting gunicorn 20.0.0
[2019-11-21 13:25:41 +0100] [28240] [INFO] Listening at: http://127.0.0.1:8001 (28240)
[2019-11-21 13:25:41 +0100] [28240] [INFO] Using worker: sync
[2019-11-21 13:25:41 +0100] [28243] [INFO] Booting worker with pid: 28243
[2019-11-21 13:25:41 +0100] [28244] [INFO] Booting worker with pid: 28244
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:45 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:46 +0100] [28240] [INFO] Handling signal: winch
[2019-11-21 13:25:46 +0100] [28240] [INFO] Handling signal: winch
```
