### ISSUE TITLE
Gunicorn freezing periodically

### ISSUE THREAD

**Issue by roshanpati** [benoitc/gunicorn#1923] opened 2018-11-23 14:09 UTC
gunicorn version 19.9.0
 Gunicorn is freezing periodically. The server keeps running ,but no request gets routed. Anyone who has faced this and resolved it?

**Comment by javabrett** [comment] 2018-11-23 22:15
Are you able to provide any other details such as anything interesting in logs, a reproducible setup or probmwm requests?

Not much to go on here yet.

**Comment by benoitc** [comment] 2018-11-27 09:45
ping @Roskgp96

**Comment by Sermus** [comment] 2018-12-24 04:17
+1. I faced the issue. I can add that setting --threads 2 or more resolves the issue.
No hints with --log-level debug. Judging by logs it just stops processing for some time, then resumes again.

**Comment by benoitc** [comment] 2018-12-24 05:19
@Sermus what does mean "freezing" in your case? Do you have any logs from gunicorn? What does your application?

**Comment by ifduyue** [comment] 2018-12-24 05:37
A guess: application or some dependent packages are sending http requests to itself synchronously

**Comment by tilgovi** [comment] 2019-01-22 08:01
If you can provide more information for debugging or a case to reproduce the problem, please open a ticket with details. Thanks!

**Comment by tilgovi** [comment] 2019-01-25 20:03
That is very strange. I'll re-open the issue. Please continue investigating if you can.

**Comment by tilgovi** [comment] 2019-01-25 20:03
If you can publish a repository with setup instructions to reproduce this that would be the best.

**Comment by joater** [comment] 2019-01-26 14:00
Hi @tilgovi , thanks for your response!

This is the repository: https://github.com/joater/gunicorn-freeze

Inside README.md you can find the steps to follow for reproducing the bug. I tested it in my notebook.

Any comments or doubts, please tell me.

**Comment by benoitc** [comment] 2019-11-22 17:43
do we have any clue about what was happening?

**Comment by tilgovi** [comment] 2019-11-23 23:22
I have not yet had a chance to look.

**Comment by AmineBenatmane** [comment] 2020-02-15 15:43
i'm facing the same issue when stress testing my flask stack (flask apps served by gunicorn behind nginx and shipped with docker) . any ideas ?

**Comment by RaviTejaMaddhini** [comment] 2020-05-27 06:46
Any update on this issue ? I am using flask server and gunicorn as wsgi.Gunicorn is not accepting any requests becoming idle after sometime and after restart it is working fine.

**Comment by tijldeneut** [comment] 2020-05-29 10:22
Same here, freezes for about 20 seconds after the amount of requests equals the amount workers. "--threads" seems to do nothing.  
I'm using default and latest CTFd, which is running on Python 2, could that be related?

**Comment by RaviTejaMaddhini** [comment] 2020-05-29 11:46
Weirdly gunicorn is throwing a 500 after being idle for some time

**Comment by smilliken** [comment] 2020-07-14 20:48
For what it's worth, I've also observed what appears to be the same issue.

It occurs for me with the combination of `gevent.monkey.patch_all()` and `multiprocessing.ThreadPool.imap_unordered`. Without either, it's fine, but with both, gunicorn workers will eventually get in a wedged state until all workers are unproductive and need to be restarted. Using `--timeout` set to a positive integer prevents the workers from being wedged indefinitely, but that doesn't help the requests they block on.

My work-around is to use `gevent.threadpool.ThreadPool` instead of `multiprocessing.ThreadPool`.

**Comment by jamadden** [comment] 2020-07-14 21:05
gevent has limited support for multiprocessing. [Anything using multiprocessing.Queue](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_thread) for example, will hang. Raw use of `multiprocessing.Process` is about all that's supported.

**Comment by smilliken** [comment] 2020-07-14 21:44
> gevent has limited support for multiprocessing. [Anything using multiprocessing.Queue](http://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_thread) for example, will hang. Raw use of `multiprocessing.Process` is about all that's supported.

Agreed! Echoes my experience exactly.

Noting in case it helps someone: gevent's event loop needs to be reinitialized in new processes and gevent has a function for this: http://www.gevent.org/api/gevent.html#gevent.reinit

**Comment by jamadden** [comment] 2020-07-14 21:49
gevent monkey-patches `fork`, and I thought (i'm the gevent maintainer) `multiprocessing.Process` to automatically re-init in child processes; there's also loop-level functions that watch for forks (IIRC, been awhile since I looked at that code). So it generally shouldn't be necessary to call that manually. I'd be interested in gevent bug reports in cases where it is.

**Comment by smilliken** [comment] 2020-07-14 22:51
> i'm the gevent maintainer
Oh hey, thank you for your work!! Gevent is awesome, I don't know what I'd do without it. I'm in your debt.

> So it generally shouldn't be necessary to call that manually. I'd be interested in gevent bug reports in cases where it is.
I've had no issue that required calling it manually (except as a sanity check while debugging).

**Comment by vjp23** [comment] 2021-02-26 03:32
+1 on this issue.

My application is quite simple. No multiprocessing whatsoever.

I'm running Flask in a Docker container on a Raspberry Pi Zero. I have another container reading sensors on a loop and dumping data to a SQLite DB and the affected container responds to incoming requests by reading the DB and returning requested data.

Logs provide no information whatsoever:

```
[2021-02-26 03:02:22 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:23 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:23 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:24 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:24 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:25 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:26 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:26 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:27 +0000] [1] [INFO] Handling signal: ttou
[2021-02-26 03:02:27 +0000] [1] [INFO] Handling signal: ttou
```

This eventually just stops. If I follow the logs with `docker logs -f <my-container>` and make a request, nothing happens in the logs, and the client just hangs indefinitely.

This seems to happen after ~12 hours of running.

**Comment by carlosdagos** [comment] 2022-07-19 01:01
Still seeing this issue. Same as above, we're using a combination of `gunicorn` and `multiprocessing.Pool`.

**Comment by benoitc** [comment] 2022-10-14 10:18
You should ensure that multiprocessus don't try to become the maste of the process it is running. Which is the issue.  

@vjp23  please open a separate issue for your problem if you still need it. I will close this old one.

**Closed by benoitc** 2022-10-14 10:18 UTC
Labels: Feedback Requested
