### ISSUE TITLE
unix socket gets deleted on worker restart

### ISSUE THREAD

**Issue by diwu1989** [benoitc/gunicorn#1298] opened 2016-06-24 21:40 UTC
We have a django app deployed on heroku with gunicorn 19.6.0
It is binding to a unix socket that's used by Nginx.

These are the options that we're using:

```
  --max-requests 500 \
  --max-requests-jitter 25 \
  --preload \
  --threads 2 \
  --timeout 27 \
  --workers 3 \
  --bind unix:/tmp/nginx.socket
```

What we're seeing is that the socket file disappears after a while.
Downgraded to gunicorn 19.4.5 and things are working fine.

Is the nginx socket file being deleted accidentally?

**Comment by benoitc** [comment] 2016-06-25 14:56
@diwu1989 do you have any gunicorn logs during th time int happen? It would help to figure what's happening. I can't reproduce it for now.

**Comment by diwu1989** [comment] 2016-06-26 01:35
yes i realize my initial context doesn't provide enough, Im going to try to create a repro steps to post

**Comment by diwu1989** [comment] 2016-06-26 05:26
here's one snippet of log I collected while rebooting a dyno
```
2016-06-26T05:24:48.691401+00:00 app[web.1]: [2016-06-26 05:24:48 +0000] [23] [ERROR] Exception in worker process
2016-06-26T05:24:48.691403+00:00 app[web.1]: Traceback (most recent call last):
2016-06-26T05:24:48.691404+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
2016-06-26T05:24:48.691405+00:00 app[web.1]:     worker.init_process()
2016-06-26T05:24:48.691406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/gthread.py", line 109, in init_process
2016-06-26T05:24:48.691406+00:00 app[web.1]:     super(ThreadWorker, self).init_process()
2016-06-26T05:24:48.691407+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 132, in init_process
2016-06-26T05:24:48.691408+00:00 app[web.1]:     self.run()
2016-06-26T05:24:48.691408+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/gthread.py", line 240, in run
2016-06-26T05:24:48.691409+00:00 app[web.1]:     s.close()
2016-06-26T05:24:48.691410+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/sock.py", line 123, in close
2016-06-26T05:24:48.691411+00:00 app[web.1]:     os.unlink(self.cfg_addr)
2016-06-26T05:24:48.691411+00:00 app[web.1]: OSError: [Errno 2] No such file or directory: '/tmp/nginx.socket'
```

**Comment by diwu1989** [comment] 2016-06-26 05:36
this seems to be what's causing the socket to disappear
```
7-9d17-e7793fb5b4d7 fwd="52.33.79.242" dyno=web.1 connect=0ms service=3ms status=200 bytes=162
2016-06-26T05:35:11.409075+00:00 app[web.1]: [2016-06-26 05:35:11 +0000] [23] [DEBUG] GET /
2016-06-26T05:35:11.409329+00:00 app[web.1]: [2016-06-26 05:35:11 +0000] [23] [INFO] Autorestarting worker after current request.
2016-06-26T05:35:11.410194+00:00 app[web.1]: [2016-06-26 05:35:11 +0000] [23] [DEBUG] Closing connection.
2016-06-26T05:35:11.787756+00:00 heroku[router]: at=info method=GET path="/" host=gunicorn.herokuapp.com request_id=9899ce58-1450-4427-8d2a-9201949eae72 fwd="52.33.79.242" dyno=web.1 connect=0ms service=3ms status=200 bytes=162
2016-06-26T05:35:11.774464+00:00 app[web.1]: [2016-06-26 05:35:11 +0000] [23] [DEBUG] GET /
2016-06-26T05:35:11.775451+00:00 app[web.1]: [2016-06-26 05:35:11 +0000] [23] [DEBUG] Closing connection.
2016-06-26T05:35:11.775798+00:00 app[web.1]: [2016-06-26 05:35:11 +0000] [23] [INFO] Worker exiting (pid: 23)
2016-06-26T05:35:11.800646+00:00 app[web.1]: [2016-06-26 05:35:11 +0000] [35] [INFO] Booting worker with pid: 35
2016-06-26T05:35:12.140399+00:00 heroku[router]: at=info method=GET path="/" host=gunicorn.herokuapp.com request_id=fecd3f83-46f4-46f9-aee1-eae85f9ae626 fwd="52.33.79.242" dyno=web.1 connect=0ms service=1ms status=502 bytes=311
2016-06-26T05:35:12.138120+00:00 app[web.1]: 2016/06/26 05:35:12 [crit] 29#0: *442 connect() to unix:/tmp/nginx.socket failed (2: No such file or directory) while connecting to upstream, client: 10.93.192.30, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/tmp/nginx.socket:/", host: "gunicorn.herokuapp.com"
```

**Comment by diwu1989** [comment] 2016-06-26 05:37
Since im running with multiple workers, it seems that whenever one of them is autorestarting, as part of the worker exiting, the unix socket would get wiped
`Autorestarting worker after current request.`
`Worker exiting (pid: 23)`
`Booting worker with pid: 35`
`*442 connect() to unix:/tmp/nginx.socket failed (2: No such file or directory) while connecting to upstream`

**Comment by diwu1989** [comment] 2016-06-26 05:43
just tested gunicorn 19.5.0, it's fine there

**Comment by diwu1989** [comment] 2016-06-26 06:08
to reproduce, clone this repo https://github.com/diwu1989/gunicorn-socket-bug
deploy to heroku app, then run apache bench on it to trigger the behavior

**Comment by benoitc** [comment] 2016-06-26 09:13
@diwu1989 The code you reference in the old version was not present in a stable release. Anyway in the current version the only reason the socket can disappear is when gunicorn has quit or has been terminated (ie when the arbiter die). Do you have any production logs that shows a restart or termination of gunicorn?

 I've no available account on heroku right now, but will try to create one to test it on monday.

**Comment by benoitc** [comment] 2016-06-26 09:19
Sorry I missed the first log. I think there is a bug in the thread worker. it shouldn't close the socket there. I will have a closer look ASAP on it.

**Comment by diwu1989** [comment] 2016-06-26 09:44
i dont think this is a heroku specific problem, it looks like gthread worker will end up deleting the unix socket when they reach their lifespan limit (if the max request setting is set)

**Comment by tilgovi** [comment] 2016-06-27 00:46
@benoitc it should close the socket there

I may have made a mistake in reviewing c62cf2f5009a1d18b3ccda58e42b88b47dffbaa1. We made the change so that only one arbiter will close the socket, and removed the protections in the socket's `close` method. However, workers still close the socket.

The workers _should_ close the socket, though, because otherwise the OS still thinks there is a listener during graceful shutdown when what we want is immediate rejection of new connections so that load balancers and reverse proxies can fail over.

Maybe we should just make `unlink` explicit and not have it implied by `close`. Then, the top arbiter can explicitly unlike those sockets that should be unlinked.

**Comment by diwu1989** [comment] 2016-07-16 04:19
when do you guys expect to have this fixed?

**Comment by tilgovi** [comment] 2016-07-16 19:41
I'm still waiting for a response to my last comment, @diwu1989. What do you think?

**Comment by benoitc** [comment] 2016-07-16 19:55
@tilgovi before that we only have a barrier checking if the parent was actually unlinking the socket. Maybe we should just keep that? Ie. we keep the parent pid when creating the socket. If the pid is different we don't unlink. Thoughts?

**Comment by benoitc** [comment] 2016-07-16 19:56
@diwu1989 we will try to make a release during the coming week.

**Comment by tilgovi** [comment] 2016-07-16 19:59
Yes, we need to keep the barrier for `unlink`. What I am saying is we _also_ need to make `unlink` explicit so when the workers close the socket they don't unlink it.

**Comment by tilgovi** [comment] 2016-07-16 19:59
So then within the conditional in the arbiter only we would explicitly call `unlink`.

**Comment by benoitc** [comment] 2016-07-16 20:13
why making it explicit? The socket is only created on the arbiter, so there is no chance that a worker could unlink it. Something like:

```python
def close(self):
   if (os.pid() == self.parent_pind): os.unlink(self.fd)
   ...
```

if we make it explicit, then there is no need to have the barrier I described. What did I miss?

**Comment by tilgovi** [comment] 2016-07-17 18:21
I think you may be forgetting again why the workers must explicitly close the socket. They do this for graceful shutdown. If the socket is closed by all processes the operating system will not hold new, half-open connections. It will reject them, letting downstream load balancers shift traffic instantly.

If the workers always exited right after they closed the socket, they could simply exit. Instead, the workers need to explicitly close the socket sometimes, but they should not unlink it.

A worker is not the only place the socket is closed before Gunicorn shuts down. The other place is where an old arbiter exits. The barrier is there to protect an exiting arbiter from closing the socket when another arbiter still exists and Gunicorn is not exiting.

The original report was about arbiter causing unlink. We fixed that, but in the meantime I fixed every worker type to explicit close as soon as graceful shutdown is triggered. Now we have a new case where unlink is called.

I'm suggesting that we make unlink explicit. You're sort of correct that the barrier is not necessary around the close operation. It is only necessary around the unlink.

If unlink were explicit, the workers could close without worrying about unlink, the arbiters could close without unlink, and the current conditional check could ensure that only one arbiter performs an explicit unlink, separate from close.

**Comment by benoitc** [comment] 2016-07-17 18:55
I don't follow... The unlink in the given snippet onlyt unlink if it's closed by the parent (pid) that created the socket. 

I'm not against having an explicit unlink, so let's do that, it's simpler.

**Comment by benoitc** [comment] 2016-07-17 19:07
please review #1309 for that :)

**Comment by tilgovi** [comment] 2016-07-17 19:31
Sometimes the PID that unlinks it is not the PID that created it, such as after a USR2. Just checking the current and previous PID is not sufficient to cover all cases. That's why we introduced the explicit tracking of which arbiter is responsible to unlink.

**Comment by benoitc** [comment] 2016-07-17 19:33
@tilgovi well the parent pid would have been set each time the socket is initialised :) but anyway the patch above use explicit unlink. Let me know

**Comment by tilgovi** [comment] 2016-07-17 19:45
Thanks for writing the patch. I'm mobile but will review in some hours.

**Comment by diwu1989** [comment] 2016-12-22 02:41
hello, would be very happy to see this fixed and a new release this year, thanks

**Comment by tilgovi** [comment] 2016-12-23 02:33
@diwu1989 is it possible for you to test the branch at #1310?

**Comment by diwu1989** [comment] 2016-12-27 05:00
just tested that branch and it does fix the problem with restarts

**Comment by tilgovi** [comment] 2016-12-27 05:14
@diwu1989 thanks so much. I'm going to try to get that merged and released as soon as possible.

**Comment by diwu1989** [comment] 2016-12-27 05:28
thanks and have a good holiday

**Closed** 2016-12-27 22:01 UTC
Labels: Bug, Feature/Core, Feature/Worker, Feedback Requested

**Comment by tomochikahara** [comment] 2017-02-14 10:01
Hi, I'm faced this problem in production servers.
What version will you include the fix?
