### ISSUE TITLE
Can't boot eventlet workers with eventlet 0.21.0

### ISSUE THREAD

**Issue by jwg4** [benoitc/gunicorn#1584] opened 2017-09-06 16:48 UTC
Eventlet workers fail to boot using the most recent release of eventlet:

To reproduce this I am using the minimal app from http://docs.gunicorn.org/en/latest/run.html

Error message:
```
(venv) jack@neptune-vm:~/z/test_gunicorn$ gunicorn -b 0.0.0.0:5015 -w 4 myapp:app -k eventlet
[2017-09-06 17:40:13 +0000] [8760] [INFO] Starting gunicorn 19.7.1
[2017-09-06 17:40:13 +0000] [8760] [INFO] Listening at: http://0.0.0.0:5015 (8760)
[2017-09-06 17:40:13 +0000] [8760] [INFO] Using worker: eventlet
[2017-09-06 17:40:13 +0000] [8765] [INFO] Booting worker with pid: 8765
[2017-09-06 17:40:13 +0000] [8765] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    self.patch()
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 91, in patch
    hubs.use_hub()
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 38, in get_default_hub
    import eventlet.hubs.epolls
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 27, in <module>
    from eventlet.hubs.hub import BaseHub
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/home/jack/z/test_gunicorn/venv/local/lib/python2.7/site-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
[2017-09-06 17:40:13 +0000] [8765] [INFO] Worker exiting (pid: 8765)
[2017-09-06 17:40:13 +0000] [8760] [INFO] Shutting down: Master
[2017-09-06 17:40:13 +0000] [8760] [INFO] Reason: Worker failed to boot.
```

System details:
```
(venv) jack@neptune-vm:~/z/test_gunicorn$ uname -a 
Linux neptune-vm 4.4.0-65-generic #86-Ubuntu SMP Thu Feb 23 17:49:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
(venv) jack@neptune-vm:~/z/test_gunicorn$ python --version
Python 2.7.12
(venv) jack@neptune-vm:~/z/test_gunicorn$ pip freeze
enum-compat==0.0.2
enum34==1.1.6
eventlet==0.21.0
greenlet==0.4.12
gunicorn==19.7.1
```

To be clear, this works with eventlet 0.20.0. I reported this as a bug to eventlet. I posted to what seemed to be a related bug https://github.com/eventlet/eventlet/issues/401 Based on the help of people there, it seems to be a bug which is not related to the eventlet bug in that issue. However, changes in eventlet seem to have caused this problem firstly to appear, and secondly to be caught as an exception by their new code for monkey-patching the monotonic clock. This explains why I got the same error message as the other users who were encountered the (now fixed) eventlet bug.

**Comment by geofft** [comment] 2017-09-06 16:52
The specific problem as I understand it is that, as of eventlet 0.21, `eventlet.hubs.use_hub()` calls `import monotonic`, which calls `ctypes.util.find_library`, which runs `ldconfig -p` in a subprocess (using either `os.popen` or `subprocess.Popen` depending on your Python version). Waiting on that child process fails, because gunicorn installs a SIGCHLD handler that waits on all children, so ldconfig has already been waited on by the time control returns to `ctypes.util.find_library`.

If gunicorn can delay installing the SIGCHLD handler until after `hubs.use_hub()` is called, that should fix the problem.

**Comment by jwg4** [comment] 2017-09-06 17:00
I created a pull request as a suggestion here: https://github.com/benoitc/gunicorn/pull/1585 This has apparently fixed the problem for me, in that I can run gunicorn, so I thought it might be useful. However, I might be completely wrong about how this would affect gunicorn's worker management, so please ignore it if it's misguided.

**Comment by jwg4** [comment] 2017-09-06 17:05
It might be difficult to not add the SIGCHLD handler until before `hubs.use_hubs()` is called, since gunicorn wants to be able to handle the death of a worker even if it hasn't yet been correctly set up, and it wants to do this in a way that is independent of which worker is used.

**Comment by benoitc** [comment] 2017-09-07 19:45
@jwg4 thanks will have a closer look over the week-end on the issue. 

Probably a silly question but why the check isn't done during the package installation instead of doing it at runtime?

**Comment by benoitc** [comment] 2017-09-11 07:20
@jwg4 i'm not sure how it is related though. Normally childs process outside the worker doesn't break the arbiter: https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L530-L532

The issue is more that eventlet is lazily testing a capavility of the system at startup and return a runtime error then. Which crash the worker.I'm not sure why it does that. Why doesn't it fallback to something else, instead of raising an issue. If it's required then it means you can't use eventlet at all anyway, so it's quite logic that the worker shutdown. Otherwise, it shouldn't raise a runtime error where I would expect an exception that can be catched eventually.

Alternatively what could be patched is the worker setup:
https://github.com/benoitc/gunicorn/blame/master/gunicorn/workers/geventlet.py#L90

and check for the runtime error....

**Comment by jwg4** [comment] 2017-09-11 08:42
Thanks a lot for looking at this benoitc. I don't think the worker is crashing. Rather I think the following happens:

1. Gunicorn attaches a signal handler  on SIGCHLD which will call `reap_workers'.
2. Gunicorn calls into eventlet to setup the workers.
3. eventlet while initializing the module, forks a child process (not a worker).
4. The child process completes successfully and SIGCHLD is sent to the parent process.
5. SIGCHLD is caught by gunicorn and the handler is triggered.
6. `reap_workers' is called.
7. `reap_workers' waits on the child process forked by eventlet. Since this process already closed, it retrieves the pid for this process.
8. Since the pid isn't one of the worker pids it knows about, it ignores it (as you pointed out).
9. Control reverts to the eventlet setup code.
10. eventlet waits on the pid of the child process it forked.
11. Since wait() was already called by `reap_workers', it fails to wait on the pid of the child.

Thus as you see, the problem is caused not by a runtime error, or a crash of the worker, but by the fact that gunicorn catches `SIGCHLD' for the eventlet child (gunicorn is expecting that the SIGCHLD relates to one of its own worker processes, but it's not the case), and gunicorn calling `waitpid' on the eventlet child (where eventlet expects that no-one else tries to retrieve the fact that the child terminated). I don't try here to imply that either gunicorn or eventlet is responsible or should be expected to change.

From the point of gunicorn, there are two things it could do:
1. Don't start to handle SIGCHLD until later. 
2. Don't wait on the pid of the eventlet child.

1. was suggested by eventlet. I believe it is problematic, because gunicorn wants to be already listening for a worker crash, before it starts to call any workers. Otherwise workers crashing at startup would not be cleaned up correctly.

2. is what my patch #1585 tries to do. I agree with you and @RonRothman that this also causes a race condition - if the child fails immediately after `fork()` and before adding itself to the dict of workers, it also won't be cleaned up.

I will try and confirm better that the description of 1-11 above is correct. If you have advice on a correct approach to fix this in gunicorn let me know. I will also create a separate eventlet issue since this bug was confused with another similar. They have also suggested a fix so any change to gunicorn might not be needed.

Thanks for your help.

**Comment by benoitc** [comment] 2017-09-11 13:46
@jwg4 cn you try to simply move the line https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/geventlet.py#L102 after it jas initialised the process and let me know about the result?

**Comment by jwg4** [comment] 2017-09-11 13:51
Sure @benoitc. It boots correctly for me with that change.

**Comment by benoitc** [comment] 2017-09-11 13:55
@jwg4 just to confirm, so moving that line only doesn't raise the issue above? 

I will test it myself later today anyway.

**Comment by jwg4** [comment] 2017-09-11 13:56
Exactly. I used latest gunicorn and eventlet, gunicorn startup failed. Changed the one line that you suggested, it worked with no problem.

**Comment by mathewcohle** [comment] 2017-11-02 21:21
Is there plan to fix this any time soon? :)

**Comment by benoitc** [comment] 2017-11-02 21:53
@mathewcohle i've been sidetracked but there will be a release tomorrow. Can you confirm moving the line above also worked for you?

**Comment by mathewcohle** [comment] 2017-11-02 22:30
I'll check tomorrow and let you know @benoitc.

**Comment by mathewcohle** [comment] 2017-11-03 10:05
So I've done some testing.

I was able to reproduce and fix the error for our production code (running in Docker):

* broken when I pip installed gunicorn from `https://github.com/mathewcohle/gunicorn.git`
* fixed when I used `https://github.com/mathewcohle/gunicorn.git@eb965739bbb405bbb9c07464e2e2c05dd2893783`

and also for minimal Docker app:
```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    python-dev \
    python-setuptools \
    python-pip \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install \
    eventlet \
    git+https://github.com/mathewcohle/gunicorn.git@eb965739bbb405bbb9c07464e2e2c05dd2893783

COPY test.py /home/gun/test.py

WORKDIR /home/gun

CMD gunicorn --log-level DEBUG -k eventlet test:app
```
(failed from `master`, works from `eb965739bb`)

However, I am not able to reproduce the error locally. My setup:

```bash
$ uname -a
Darwin 172-3-0-4.lightspeed.irvnca.sbcglobal.net 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ python --version
Python 2.7.14

$ pip freeze
enum-compat==0.0.2
enum34==1.1.6
eventlet==0.21.0
greenlet==0.4.12
gunicorn==19.7.1
```

Which is kind of strange. Not sure wether it's related to the fact that it's running in Docker or it's Ubuntu/Linux related.

@benoitc

**Comment by geofft** [comment] 2017-11-03 12:10
@matthewcohle That's expected—monotonic only calls a subprocess (via `ctypes.util.find_library`) on Linux or BSD. On macOS it hardcodes the library path. https://github.com/atdt/monotonic/blob/master/monotonic.py

**Comment by mathewcohle** [comment] 2017-11-03 15:22
Should I create PR? I mean, all credit goes to @jwg4 and @benoitc for debugging and solving the issue, it's just that I have the patch ready.

**Comment by benoitc** [comment] 2017-11-12 10:20
@mathewcohle ah sorry didn't see your last message. I just committed the patch I had . Thanks for the test anyway!

**Closed** 2017-11-12 10:19 UTC
