### ISSUE TITLE
Measure gunicorn response time for concurrent request

### ISSUE THREAD

**Issue by yanglu0106** [benoitc/gunicorn#1714] opened 2018-03-02 19:36 UTC
From my understanding and what I've seen so far, `gunicorn.request.duration` in the gunicorn instrumentation module is measuring the response time from the worker picking up the request from listener, rather than when the request hitting gunicorn.

I want to measure the latency from the request hitting gunicorn to gunicorn returning response for concurrent requests, what would the best way?

Correct me if my understanding is incorrect, and I appreciate any discussion or suggestion.

**Comment by tilgovi** [comment] 2018-03-04 00:54
What do you mean by "worker picking up the request from the listener"? The threaded worker handles requests on a separate thread from the accept, but for most workers the worker is the listener.

If you want to measure something else, maybe you need to measure it outside of Gunicorn.

**Comment by yanglu0106** [comment] 2018-03-05 16:41
Thanks, I guess you answered my question. Just to double confirm, basically we cannot measure the time of a request waiting in the queue, since the queue is on the socket.

**Comment by tilgovi** [comment] 2018-03-05 18:49
@yanglu0106 that's a good way to say it, thanks!

**Comment by sashasimkin** [comment] 2019-01-29 18:14
I'm having a similar question and use threaded worker (gthread), and I believe that this can be solved by measuring time from `accept` and up to the point when the response is generated and handed upstream.

Due to the fact that threaded worker handles requests in a separate thread - the time between `accept` and `response` is different from `request.duration` (and the deviation might be very big in case gunicorn is being hit by more traffic than it's capable to handle).

**Comment by tilgovi** [comment] 2019-01-29 20:18
> Due to the fact that threaded worker handles requests in a separate thread - the time between accept and response is different from request.duration (and the deviation might be very big in case gunicorn is being hit by more traffic than it's capable to handle).

I'm not sure this is true unless Gunicorn is listening on multiple sockets. The main thread will call `select` only if [there is a free handler thread](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/gthread.py#L199), but it will call `accept` and enqueue a request job for each socket that is ready with a new connection. If there is only one listener socket, that means only one job is queued.

We could make this the behavior even with more than one listener but checking `self.nr_conns` in the inner loop, but we'd have to take care not to starve some listeners.

With the current behavior and one listener socket, Gunicorn should not accept any connection until a request handling thread is ready (`self.nr_conns < self.worker_connections`).

**Comment by sashasimkin** [comment] 2019-01-31 14:05
Oh, I missed the part that gunicorn will call `accept` only _after_ `select`, and call to `select` is guarded by `self.nr_conns < self.worker_connections`.

Yet, the condition `self.nr_conns < self.worker_connections` is not equal to "there's a free handler thread" unless I'm missings something. Because `self.worker_connections` is not tied to the number of threads and the default for it is `1000` :sweat_smile: 

From what I understand setting `worker_connections` to the number of threads will practically make `gthread` worker the same as `sync`, because there will be no space for keepalive connections.

Btw, what's the intention of `worker_connections` for `gthread` worker?

----
This question is particularly related to a problem I'm having with threaded worker: gunicorn will handle requests for which the connection was already closed, but I'll open a separate issue for that with more examples.

**Comment by tilgovi** [comment] 2019-01-31 17:09
My apologies for the error and thank you for the correction. I read too quickly and I'm not as familiar with the thread worker.

I'll read a bit closer and answer some of your questions when I can.

**Comment by tilgovi** [comment] 2019-01-31 17:10
> gunicorn will handle requests for which the connection was already closed, but I'll open a separate issue for that with more examples

I'll be very interested to know what you find. If that's the case, it may even be the root cause for some other issues.

**Comment by benoitc** [comment] 2019-11-22 20:20
closing issuse , discussion continue in #1976

**Closed by benoitc** 2019-11-22 20:20 UTC
