### ISSUE TITLE
'AsyncIOMainLoop' object has no attribute '_callbacks'

### ISSUE THREAD

**Issue by bingwork** [benoitc/gunicorn#2119] opened 2019-09-26 09:15 UTC
@benoitc 
when I use gunicorn and tornado,  set max_requests=12, so when gtornado work request num > 12, then self.alive = False, when heartbeat run, self.ioloop._callbacks will causes error below.
mainly because tornado<=2.4.1 the ioloop has _callbacks, but it's too old. tornado bigger than this version, IOLoop will not have _callbacks.
my solution is set max_requests=70000, hope enough to work.
any better way? thx.
and can you help to fix this errors. thx.

2019-09-26 08:00:35,577 - 9 - tornado.application - ERROR - Exception in callback <bound method TornadoWorker.heartbeat of <gunicorn.workers.gtornado.TornadoWorker object at 0x7faa363dfc90>>
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 1229, in _run
return self.callback()
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gtornado.py", line 69, in heartbeat
if not self.ioloop._callbacks:
AttributeError: 'AsyncIOMainLoop' object has no attribute '_callbacks'

**Comment by tomwojcik** [comment] 2019-11-07 13:43
@benoitc 

We recently upgraded tornado into 5.x and we bumped into this issue. The newest tornado version is 6.x. I see that you have a compatible version for 5 on master right now which does

`TORNADO5 = tornado.version_info >= (5, 0, 0)`

and then

`
                if TORNADO5:
                    for callback in self.callbacks:
                        callback.stop()
                    self.ioloop.stop()
                else:
                    if not self.ioloop._callbacks:
                        self.ioloop.stop()
`

but the latest version of gunicorn that has been published (19.9.0) doesn't support tornado 5, which is the cause of this issue.

Do you plan to release tornado 5 support (master) soon?

**Comment by tomwojcik** [comment] 2019-11-13 11:19
@bingwork 20.0.0 has been released with the necessary change.

**Closed** 2019-11-23 23:05 UTC
Labels: Feedback Requested, Investigation
