### ISSUE TITLE
communication problem in a containerized environment.

### ISSUE THREAD

**Issue by bvivi57** [benoitc/gunicorn#2367] opened 2020-06-29 21:49 UTC
Hi

I try to follow the following tutorial 
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-full-text-search

I'm trying to make my flask application talk to an Elasticsearch server. It works when my application is delivered by gunicorn launched directly on a server, but it doesn't work when I switch to a container (docker).

I use exactly the same code and the same gunicorn parameter. I have the impression that in container, the request is sent to Elasticsearch but the answer is not considered by my application. However, I have the trace of the request on the Elasticsearch server and its response to my application in the network captures.

Is there a specific setting to use gunicorn in a container ? 

I specify that I have exactly this behavior error on a server or on my workstation. 

I always launch gunicorn with the following command:

`exec gunicorn -b 0.0.0.0:5000 --access-logfile - --error-logfile - microblog:app`

If the command is launched directly on a server or on my workstation, everything works and I can request my remote Elasticsearch server without incident.

If it is launched in a container running on a server or on my computer, my application works, I can access the site, but the requests to ELK do not return any result, while I can see the requests arriving on the Elasticsearch server.

My server : Ubuntu 20.10
Docker : 19.03.8
gunicorn : 20.0.4

**Comment by psyonara** [comment] 2020-07-02 07:14
I'm having a problem which may or may not be related. Wanted to post a separate issue, but thought it might be worth finding out if it's the same root problem.

I have gunicorn running in a container as well, serving an API. The one API endpoint does a call to Google's Vision API. This request just hangs. But when I switch to something other than gunicorn, it works flawlessly. I've tried older versions of gunicorn (back to 19.9 from 2018), but the same thing happens.

**Comment by benoitc** [comment] 2020-07-02 07:24
there is no specific settings for containers, just make sure to expose correctly the port or the unix socket you are using. Without any log it's hard to say what is happening though.

@psyonara please open a ticket with a way to reproduce your issue. Any useful log is welcome also.

**Comment by psyonara** [comment] 2020-07-02 07:40
I'm going to try it outside of a container as well, just to see if it persists or not. Will log an issue if it persists.

**Comment by psyonara** [comment] 2020-07-06 06:26
I believe the problem is addressed in this article, and it sounds like it can be corrected by modifying the working directory for gunicorn.
https://pythonspeed.com/articles/gunicorn-in-docker/

**Comment by jab** [comment] 2020-07-15 01:10
> I believe the problem is addressed in this article, and it sounds like it can be corrected by modifying the working directory for gunicorn.

To be clear, not the work-_ing_ directory (`os.getcwd()`), the work-_er tempory_ directory (`--worker-tmp-dir`). The half-minute hangs described in that article occur when the worker tmp dir is backed by a _remote_ disk (e.g. AWS EBS) which is much slower to access than the tmpfs- (memory-) backed filesystem that `/tmp` often uses in typical Linux hosts. Note also that the proposal from the article to pass `--worker-tmp-dir=/dev/shm` to avoid this issue may cause issues of its own.

Just opened #2381 in case it's worth making that issue easier to debug.

**Closed** 2023-05-07 18:14 UTC
