### ISSUE TITLE
Interrupted connections in 19.4.0+ on Heroku

### ISSUE THREAD

**Issue by hheimbuerger** [benoitc/gunicorn#1158] opened 2015-12-02 21:12 UTC
(I know this bug report is short and incomplete but I'm low on time. Wanted to report it anyway, feel free to ask and I'll extend it when I can.)

I'm serving static files using whitenoise 2.0.6 and Python 2.7.10 on Heroku via gunicorn. This worked fine in gunicorn 19.3.0. When I upgrade to 19.4.0 or 19.4.1, these static files are only partially delivered.

Here's what it looks like accessing jquery-1.11.1.js with Chrome:

![2015-12-02_2210](https://cloud.githubusercontent.com/assets/159414/11544330/a176a24c-9941-11e5-889a-2a47c6cbeff2.png)

See how the content length differs from the actual delivered size and how the file is incomplete?

Here's what Heroku shows:

    Nov 27 10:40:30 still-depths-9379 heroku/router: sock=backend at=error code=H18 desc="Server Request Interrupted" method=GET path="/static/js/libs/jquery-1.11.1.js" host=myapp.herokuapp.com request_id=63fdbac8-11f3-4725-88ed-be627d4fdd2b fwd="79.192.97.113" dyno=web.1 connect=1ms service=9ms status=503 bytes=291

**Comment by benoitc** [comment] 2015-12-04 10:51
it's probably a duplicate of #1156 can you try the fix there?

**Comment by hheimbuerger** [comment] 2015-12-04 13:42
@benoitc I see no indication that #1156 is related to this. What makes you think so?

**Comment by benoitc** [comment] 2015-12-04 14:46
because static files may use sendfile. also both describe rhe same symptoms
imo. did you test the change?

**Comment by godshall** [comment] 2015-12-05 00:10
I had the same problem and I was directed to this issue by Heroku support.  I added --no-sendfile to the gunicorn command in my Procfile and the static files are working correctly now.

**Comment by benoitc** [comment] 2015-12-06 15:14
@hheimbuerger sorry it was #1155 ?. Can you check with the latest master? @godshall should also fix your issue. Let me know

**Comment by hheimbuerger** [comment] 2015-12-06 20:01
@benoitc Ah yes, #1155 indeed sounds exactly like the issue I was having! Didn't have a chance to test the fix yet, but I'm very confident that this will cover my issue as well (I'm doing nothing special here at all really).

**Closed** 2015-12-06 20:01 UTC
