### ISSUE TITLE
[DEBUG] Closing connection

### ISSUE THREAD

**Issue by roman-telepathy-ai** [benoitc/gunicorn#1952] opened 2019-01-15 13:39 UTC
hi all,

I am using `gunicorn` since 1.5 years and so far no issues. But couple days ago, I noticed many messages in the log below.

**My question: what does `[DEBUG] Closing connection` stands for?**
```
....
[2019-01-15 11:50:38 +0000] [18] [DEBUG] Closing connection. 
[2019-01-15 11:51:37 +0000] [18] [DEBUG] Closing connection. 
[2019-01-15 11:51:38 +0000] [18] [DEBUG] Closing connection. 
[2019-01-15 11:52:37 +0000] [18] [DEBUG] Closing connection. 
....
```

My application:
* flask rest
* endpoint is POST method, takes about 30ms to process data and send 200
* gunicorn is with `gthead`
* this is running in Docker container with `CMD ["gunicorn", "-c", "guniconf.py", "wsgi"]`
* no other special things to mention

```
# guniconf.py
bind = '%s:%s' % ('0.0.0.0', 8000)

workers = 1
worker_class = 'gthread'
threads = 4
timeout = 30

daemon = False

errorlog = '-'
loglevel = 'debug'
accesslog = '-'
capture_output = True
```

**Comment by javabrett** [comment] 2019-01-16 12:23
I suppose being logged from:

https://github.com/benoitc/gunicorn/blob/ba0d784960be9d1e30e47e0d8b03f52c30590a0f/gunicorn/workers/gthread.py#L337

**Comment by tilgovi** [comment] 2019-01-22 08:32
Did you recently switch to the threaded worker or switch the log level?

**Comment by roman-telepathy-ai** [comment] 2019-01-25 11:34
hi all, thx for reply.

The log level is not issue here. I discovered that just by accident.

The service was running in different environments without any issues, and somehow now, by using RESTler or Curl, each worker is now blocked for 60sec. after I debug messages on the console.

I can not explain, why that happens - I am using `gthreads` and now they get blocked, as the gunicorn maintains the open connection for 60sec. I switched to another web server, on the same machine, same environment, and the issue is gone. So it was definitely gunicorn (1 process, 4 threads).

I have few more service which are running with guni, and they seems to be OK. So I will need to investigate the source a bit more.

I have often read about `keep-alive` here... so need to validate.

r

**Comment by benoitc** [comment] 2019-01-29 08:45
@roman-telepathy-ai well what do you mean by switching to another webserver?  

Anyway anything that would help us to reproduce the issue would be interesting. Were you always use the gthread worker? What changed ? What changed on the environment?  How many requests are we talking about, which kind of load? Which kind of requests?  Can it be reproduced outside your application with something maybe simpler?

**Comment by jsbroks** [comment] 2019-03-15 21:32
@benoitc I'm getting this issue as well. 
```
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/2325
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/2306
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/914
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/2304
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/1603
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
```
This issue started occuring once I switched to using `eventlet` (since I added flask-socket-io). The [project](https://github.com/jsbroks/coco-annotator) is completely open source which might help reproducing the issue. Here are some of my observations:

- Running the production build locally I dont get this error and requests are handled async
- Running production though nigix I get spammed this error and requests are sync
- Running the development build I get spammed this error but async request are handled fine

Please let me know how I can help out, thanks!

**Comment by jsbroks** [comment] 2019-03-18 19:17
@benoitc @tilgovi  I'm getting this issue as well. 
```
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/2325
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/2306
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/914
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/2304
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
[2019-03-15 21:24:02 +0000] [9] [DEBUG] GET /api/image/1603
[2019-03-15 21:24:02 +0000] [9] [DEBUG] Closing connection. 
```
This issue started occuring once I switched to using `eventlet` (since I added flask-socket-io). The [project](https://github.com/jsbroks/coco-annotator) is completely open source which might help reproducing the issue. Here are some of my observations:

- Running the production build locally I dont get this error and requests are handled async
- Running production though nigix I get spammed this error and requests are sync
- Running the development build I get spammed this error but async request are handled fine

Please let me know how I can help out, thanks!

**Comment by heilaaks** [comment] 2019-04-19 17:22
Observed the same log from Gunicorn: `Closing connection.` In my case this was coming after adding Docker healthcheck with `nc` command like:

```bash
HEALTHCHECK --interval=10s --timeout=5s CMD nc -zv 127.0.0.1 9090 || exit 1
```

After removing this periodic healthcheck from container running the server, the log was gone. The original issue here seems to have one minute interval for this log when ran in a container. This may indicate periodic health check or polling in similar manner than above.

With logs enabled, I did not find out a nice way to do the healthcheck from command line without the `Closing connection` log.

**Comment by benoitc** [comment] 2019-11-22 20:53
this error is expected in debug mode, since the close header is sent.

**Closed by benoitc** 2019-11-22 20:53 UTC
Labels: Feedback Requested

**Comment by TimotheeJeannin** [comment] 2019-12-04 09:15
I also have this issue. It appeared a few days ago on my production system. For every request receive, I also have a `[DEBUG] Closing connection` . 

@benoitc When you say it is supposed to happen in debug mode, what do you mean? It is supposed to happen when the log level is set to `debug`? I don't see anything about a "debug mode" in the documentation: https://docs.gunicorn.org/en/stable/search.html?q=debug&check_keywords=yes&area=default

**Comment by yonromai** [comment] 2021-07-08 19:29
@TimotheeJeannin Did you figure out what caused this issue?

**Comment by TimotheeJeannin** [comment] 2021-07-09 11:31
> @TimotheeJeannin Did you figure out what caused this issue?

I did not figure out what the exact cause was. But I have upgraded all my dependencies and the issue is gone. 
Here is what I have in production right now (among other things):

```
Werkzeug==1.0.1
Flask==1.1.2
gunicorn==20.0.4
gevent==20.9.0
```

**Comment by yonromai** [comment] 2021-07-12 17:22
Thank you @TimotheeJeannin, the problem happened to me as I was changing package versions (other than gunicorn). There's probably some internal conflicts between dependencies.
