### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory in AWS container but not in regular aws instance.

### ISSUE THREAD

**Issue by jltchiu** [benoitc/gunicorn#1377] opened 2016-10-21 16:18 UTC
Hi All,

So I am using gunicorn + flask to develop a web service. When I am running on a standard aws cloud instance, it works properly with the command `gunicorn process:APP -b 0.0.0.0:8080 -w 1 -k gevent --threads 4 --timeout 10 --preload` and it takes about 1.7G of memory. However, when I am trying to put it into a container, it always shows the error as below. The container has 3 GB of memory so I don't think the memory is insufficient, is there any setting (like swap memory?) that need to be set to make sure this works properly? 

Unhandled exception in main loop","Traceback (most recent call last):"," File \"/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py\", line 189, in run"," self.manage_workers()"," File \"/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py\", line 524, in manage_workers"," self.spawn_workers()"," File \"/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py\", line 590, in spawn_workers"," self.spawn_worker()"," File \"/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py\", line 546, in spawn_worker"," pid = os.fork()","OSError: [Errno 12] Cannot allocate memory"],"command":"/bin/sh -c gunicorn process:APP -b 0.0.0.0:8080 -w 1 -k gevent --threads 4 --timeout 10 --preload"

**Comment by benoitc** [comment] 2016-10-25 08:00
How much your application is using the  memory? By itself gunicorn don't use much memory and can run on hardware with 256MB of ram.

**Comment by jltchiu** [comment] 2016-10-25 14:16
When I do my development on AWS t2.medium instance, The Gunicorn+Flask works well with about 2G memory. When using on Amazon ECS, I am assigning it 3G of memory so I think the physical memories should not be an issue. 

On AWS, I just go to the terminal, and run
gunicorn process:APP -b 0.0.0.0:8080 -w 1 -k gevent --threads 4 --timeout 10 --preload

and everything works properly.

I tried to do the same thing by using container, and now it's saying out of memory issue, so I am not quite sure what's happening.

**Comment by benoitc** [comment] 2016-10-27 07:04
@jltchiu so first I think you want:

`gunicorn process:APP -b 0.0.0.0:8080 -w 4 -k gevent --timeout 10 --preload`

the `--threads` setting only work with the sync worker. The command line you are currently using only use 1 worker, and then let gevent handle all the requests in its event loop.

Secondly, did you try to use another worker? Do you reproduce it? Can you paste me the memory usage / workers?

**Comment by jltchiu** [comment] 2016-10-27 20:10
@benoitc 

Just an update on this, this magically go solved on my end. I think what happen is since my service lacks a healthcheck endpoint, so the load balancer consistently tries to kill it so whenever it tries to do anything load balancer just killed the task, hence there's no way it's gonna get any resource I guess (This issue is resolved after I added the healthcheck endpoint in my app)

One other question I have is, it seems to me that adding extra workers won't increase the memory usage? So I guess I can set as many work as I want and it's always taking about 2G memory? But that's off the topic of this discussion. Anyway it's working now, thanks.

**Comment by tilgovi** [comment] 2016-12-21 03:24
Since the problem has gone away, I'll close the issue.

To answer your question, @jltchiu, workers will usually start with all memory shared but will copy-on-write as per the semantics of the `fork()` system call and will also consume more memory by handling requests. When gunicorn is idle, additional workers do not take much memory, but when each worker is leaded they will each consume more memory.

**Closed by tilgovi** 2016-12-21 03:24 UTC
Labels: Discussion
