### ISSUE TITLE
OSError 9 in murder_workers in Gunicorn 0.12.2

### ISSUE THREAD

**Issue by migurski** [benoitc/gunicorn#381] opened 2012-07-23 20:46 UTC
I see an OSError from this line periodically: https://github.com/benoitc/gunicorn/blob/fc300cc23c4c84a743c228202b64379d1621005e/gunicorn/arbiter.py#L379

Here's the complete traceback:

```
2012-07-19 04:02:22 [16302] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/gunicorn-0.12.2-py2.6.egg/gunicorn/arbiter.py", line 161, in run
    self.murder_workers()
  File "/usr/local/lib/python2.6/dist-packages/gunicorn-0.12.2-py2.6.egg/gunicorn/arbiter.py", line 379, in murder_workers
    diff = time.time() - os.fstat(worker.tmp.fileno()).st_ctime
OSError: [Errno 9] Bad file descriptor
```

I thought perhaps this might be a similar issue to #358 or #367 but it's not quite clear. Also, I see that the line has been modified in more recent versions of Gunicorn. Was it to fix this problem?

**Comment by muravitskiy** [comment] 2015-02-24 13:42
got the same error in 19.2.0

**Comment by tilgovi** [comment] 2015-02-24 18:55
I'll re-open to investigate.

**Comment by jfarrimo** [comment] 2015-03-26 23:31
I am getting the error with gunicorn 19.3.0 (running on on ubuntu 12.04) sometimes when I issue a hup signal to it.

[2015-03-26 22:21:28 +0000] [15450] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/home/instaedu/.virtualenvs/instaedu/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 180, in run
    self.murder_workers()
  File "/home/instaedu/.virtualenvs/instaedu/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 430, in murder_workers
    if time.time() - worker.tmp.last_update() <= self.timeout:
  File "/home/instaedu/.virtualenvs/instaedu/local/lib/python2.7/site-packages/gunicorn/workers/workertmp.py", line 50, in last_update
    return os.fstat(self._tmp.fileno()).st_ctime
OSError: [Errno 9] Bad file descriptor

**Comment by heyman** [comment] 2015-07-26 11:25
I've also seen this error with 19.3.0 running within a Docker container.

**Comment by tilgovi** [comment] 2015-12-31 07:39
I was just investigating #1118 and so I've been reviewing the signal handlers and potential race conditions in worker shutdown. I think it's possible for a dead worker to be reaped while it's concurrently being checked for timeout.

I'm going to start by trying to fix this before continuing with #1118.

**Comment by benoitc** [comment] 2015-12-31 10:12
@tilgovi related to docker it may be due to the process are handled by the PID1, the worker may have been closed but eh PID is kept or something like it:
http://blog.dscpl.com.au/2015/12/issues-with-running-as-pid-1-in-docker.html

in // I will release sometimes next week a branch using the new IPC library which is removing all the gymnastic with tmp files.

**Comment by benoitc** [comment] 2016-10-16 15:55
I never reproduce that thing. Do we still reproduce it?

**Comment by benoitc** [comment] 2017-01-27 14:12
i am closing that issue. noone figured to give a reproducible way to reproduce it.

**Closed by benoitc** 2017-01-27 14:12 UTC
Labels: Bug, Investigation, Working On It
