### ISSUE TITLE
Exit status of master should be non-zero in case of error

### ISSUE THREAD

**Issue by jgehrcke** [benoitc/gunicorn#1183] opened 2016-01-18 19:23 UTC
Of course I am not 100 % sure about how this has been decided, but I would expect to see a non-zero exit code after master shutdown when a worker failed to boot. That is, this was highly surprising to me:

```
[...]
[2016-01-18 20:16:39 +0100] [8144] [INFO] Shutting down: Master
[2016-01-18 20:16:39 +0100] [8144] [INFO] Reason: Worker failed to boot.
(venv342-bouncer) [jp@jp-t450s:~/dev/bouncer]
20:16:39 $ echo $?
0
```

**Comment by vespian** [comment] 2016-01-20 11:24
:+1:

**Comment by tilgovi** [comment] 2016-02-03 21:02
:+1:

**Comment by benoitc** [comment] 2016-05-02 13:52
Actually it is expected to return with exit status `3`. Just tested it on zsh and It return what is expected:

```sh
[2016-05-02 15:50:57 +0200] [58904] [INFO] Worker exiting (pid: 58904)
[2016-05-02 15:50:57 +0200] [58901] [INFO] Shutting down: Master
[2016-05-02 15:50:57 +0200] [58901] [INFO] Reason: Worker failed to boot.
(gunicorn_py3)[examples] echo $?                                                           15:50:57  ☁  master ☂ ⚡ ✭
3
```

**Comment by jgehrcke** [comment] 2016-05-04 18:17
Hey, using bash. But both of our shells should be working fine :-) (let's assume that for now, wouldn't it be horrible if my shell didn't properly expose the exit code of the process that last terminated?)

I think for making progress, we probably need to find the difference between our cases of making the worker fail. I unfortunately do not remember how I made it fail at the time of reporting.

One thing I also cannot exclude: maybe I had gunicorn running in a wrapper (shell script, for instance)? I doubt that, but as I have unfortunately not explicitly written that above, we shouldn't exclude this.

So, next time I can hopefully provide a more complete report.

**Comment by benoitc** [comment] 2016-10-16 16:05
bump

**Comment by benoitc** [comment] 2017-01-27 14:18
no answer since awhile. closing the issue since I was not able to reproduce it myself.

**Closed by benoitc** 2017-01-27 14:18 UTC
Labels: Feature/Core, Feedback Requested, Investigation
