### ISSUE TITLE
is gunicorn use httptools parser possible?

### ISSUE THREAD

**Issue by Infixz** [benoitc/gunicorn#1668] opened 2017-12-24 16:27 UTC

**Comment by benoitc** [comment] 2017-12-24 23:40
why would you do that?

**Comment by Infixz** [comment] 2017-12-25 02:12
em my fault, it should not be an issue. But what I intend to say is gunicorn maybe can get benefit from faster http parser

**Comment by berkerpeksag** [comment] 2017-12-25 04:35
This is a duplicate of #1180. I suggested benoitc/http_parser there but we could collect other parsers too.

**Closed by berkerpeksag** 2017-12-25 04:35 UTC
