### ISSUE TITLE
Disable HTTPS connection to Gunicorn/Flask server.

### ISSUE THREAD

**Issue by nickyfoto** [benoitc/gunicorn#2685] opened 2021-11-12 16:19 UTC
```py
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
```

If I start the above flask app using Gunicorn `gthread` worker class.

`gunicorn -k gthread --log-level debug hello:app`

Whenever a client sends HTTPS request e.g. `curl -vv https://localhost:8000`, the gunicorn server will spawn a worker to deal with the request, but it does know how to handle it.

On client side, it will wait for the handshake to proceed.

```
curl -vv https://localhost:8000
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
```

Is there a way to config Gunicorn server to only accept HTTP request? For others such as HTTPS, just terminate the connection without wasting a worker for that.

**Comment by nickyfoto** [comment] 2021-11-15 16:48
this is probably a duplicate of https://github.com/benoitc/gunicorn/issues/1929

I think the discussion is on https://github.com/benoitc/gunicorn/issues/2237 which is still in progress

**Comment by javabrett** [comment] 2022-01-18 22:18
Closing as duplicate of #1929.

**Closed by javabrett** 2022-01-18 22:18 UTC
