### ISSUE TITLE
POST fails when returning >13k response on Heroku

### ISSUE THREAD

**Issue by erjiang** [benoitc/gunicorn#840] opened 2014-08-04 19:38 UTC
Hi, we hit this issue in production using Flask + Gunicorn + Heroku and couldn't find a cause or a workaround.

For one particular POST request with POST parameters, the request would fail with an H18 error (sock=backend) in Heroku's router indicating that the server closed the socket when it shouldn't have.

We started decreasing the response size of that failing endpoint until we narrowed it down to around the 13k mark. If we sent less than 13k, the response would always work. If we sent more than 13k, the response would almost always not work.

Code to reproduce this is available at https://github.com/erjiang/gunicorn-issue - just deploy the repo to Heroku as is and follow the instructions in the README.

**Comment by maximkgn** [comment] 2015-09-06 23:54
HI all,
I am experiencing the same problem. Did any of you got the chance to examine this issue more thoroughly?
@tilgovi @erjiang @benoitc 

Cheers
Maxim

**Comment by benoitc** [comment] 2015-09-16 04:20
@maximkgn are you also using flask? Any more details?

**Comment by maximkgn** [comment] 2015-09-16 09:43
I am using django 1.7. 
We had a certain post response which was always longer than 13k, and with a certain probability ~0.5 the response in the client would be truncated to a bit over 13k. In the heroku logs we saw the same h18 error, and after we made sure no error is happening in our python code, we had to conclude it happens in the gunicorn layer between heroku and our python. 
When we switched to waitress/uwsgi the bug stopped happening..

**Comment by benoitc** [comment] 2015-09-16 10:17
@maximkgn what happen if you use the `--threads` setting ?

**Comment by tilgovi** [comment] 2015-12-31 07:34
Anyone able to test this?

**Comment by cbaines** [comment] 2016-01-21 14:31
I have the same problem with flask and gunicorn (tested versions 19.3 and 19.4.5). @benoitc I tried 1, 2, and 4 threads (with the --threads) option, and it makes no difference.

Let me know if I can help test this in any way?

**Comment by benoitc** [comment] 2017-01-27 14:16
@cbaines what  the requests look like? 

Friendpaste is able to accept more than 1M posts.... so there is certainly not a limit inside gunicorn.

**Comment by benoitc** [comment] 2017-11-06 06:39
never had an answer. closing the issue since it's not reproducible. Feel free to reopen one if needed.

**Comment by erjiang** [comment] 2019-02-20 00:25
Still reproduces after updating dependencies to include Flask 1.0.2 and gunicorn 19.9.0. Might be nice to get the attention of someone at Heroku about this though - I hear they have some dedicated Python people.

See latest commit here: https://github.com/erjiang/gunicorn-issue/

**Comment by mountainhound** [comment] 2019-03-10 19:09
I am also receiving this H18 error on a large GET request regularly.

**Comment by mountainhound** [comment] 2019-03-12 16:45
> Still reproduces after updating dependencies to include Flask 1.0.2 and gunicorn 19.9.0. Might be nice to get the attention of someone at Heroku about this though - I hear they have some dedicated Python people.
> 
> See latest commit here: https://github.com/erjiang/gunicorn-issue/

I created a support ticket on Heroku. Will update here if anything useful comes from it.

**Comment by mountainhound** [comment] 2019-03-12 16:48
@benoitc looks like @erjiang provided a reproducible example. Could we open this back up?

**Comment by tilgovi** [comment] 2019-03-29 20:33
Re-opened. I'll self-assign and take a look when I can.

**Comment by SDCRoman** [comment] 2019-04-11 08:55
> > Still reproduces after updating dependencies to include Flask 1.0.2 and gunicorn 19.9.0. Might be nice to get the attention of someone at Heroku about this though - I hear they have some dedicated Python people.
> > See latest commit here: https://github.com/erjiang/gunicorn-issue/
> 
> I created a support ticket on Heroku. Will update here if anything useful comes from it.

Did you get a reply from heroku?

**Comment by edmorley** [comment] 2019-04-12 08:42
I was able to reproduce using the testcase at https://github.com/erjiang/gunicorn-issue (which is using gunicorn 19.9.0, Python 2.7.14, sync worker, `--workers 4`). Of note is that gunicorn's access log output reports it believes it has returned an HTTP 200.

Updating to Python 3.7.3 + gunicorn `master`, and reducing to `--workers 1` had no effect on reproducibility, however switching from sync worker to gevent made the error occur less frequently (though it still occurred). Using `--log-level debug` didn't reveal anything significant (the only additional output during the request was the `[DEBUG] POST /test1` line).  

Next I tried `--spew`, however the issue no longer occurred. This led me to try adding a `time.sleep(1)` before the `resp.close()` [here](https://github.com/benoitc/gunicorn/blob/cc8e67ea83ce1064ef605d82130ace2a3670d68a/gunicorn/workers/sync.py#L182) which similarly prevented the issue from occurring. 

As such it seems the cause is that the socket send buffer might not be empty at time of the `close()`, which can cause the response to be lost:

> Note: `close()` releases the resource associated with a connection but does not necessarily close the connection immediately. If you want to close the connection in a timely fashion, call `shutdown()` before `close()`. 

(See https://docs.python.org/3/library/socket.html#socket.socket.close)

Adding `sock.shutdown(socket.SHUT_RDWR)` ([docs](https://docs.python.org/3/library/socket.html#socket.socket.shutdown)) prior to the `sock.close()` [here](https://github.com/benoitc/gunicorn/blob/cc8e67ea83ce1064ef605d82130ace2a3670d68a/gunicorn/util.py#L294) resolved the issue for me. An alternative fix perhaps might be to use `SO_LINGER`, though that from what I've read it has trade-offs.

Docs on this subject are hard to come by, but I found:
https://stackoverflow.com/questions/8874021/close-socket-directly-after-send-unsafe
https://blog.netherlabs.nl/articles/2009/01/18/the-ultimate-so_linger-page-or-why-is-my-tcp-not-reliable

Hope that helps :-)

**Comment by edmorley** [comment] 2019-04-12 09:09
Full STR:
1. Create a free Heroku account at https://signup.heroku.com
2. Install the Heroku CLI (see https://devcenter.heroku.com/articles/heroku-cli)
3. Log into the CLI using `heroku login`
4. `git clone https://github.com/erjiang/gunicorn-issue && cd gunicorn-issue`
5. `heroku create` (this creates a free Heroku app with randomly generated name and configures a git remote named `heroku`)
6. `git push heroku master`
7. `curl --data "foo=bar" https://YOUR_GENERATED_APP_NAME.herokuapp.com/test1` (fails >75% of the time)

**Comment by erjiang** [comment] 2019-04-24 23:10
@tilgovi Sounds like @edmorley produced a plausible explanation of what's wrong. Are you able to take a look and see what the right fix is? I could also submit a PR to add `sock.shutdown()` but I don't know enough to say whether it's the right fix or whether it would negatively affect other situations.

**Comment by stapetro** [comment] 2019-05-15 18:15
Hello, I hit the same problem with 503 KB response size. Response data is JSON array.
**Observed behavior** is:
1. I see truncated response body and the http client (Chrome, curl) is still waiting for the response.
2. ~75% of requests experience response time between 120-130 seconds. The remaining requests resolve under 400 ms.
3. Requests with small response size are fast.

**It's reproducible** on both:
1. local Docker installation on Windows 10
2. Running docker container on AWS ECS

**Runtime environment setup**
[meinheld-gunicorn-docker](https://github.com/tiangolo/meinheld-gunicorn-docker) image tagged as _python3.6_ with Python 3.6.7, [Flask](http://flask.pocoo.org/) 1.0.2, [flask-restplus](https://flask-restplus.readthedocs.io/en/stable/) 0.12.1, simpe [Flask-caching](https://pythonhosted.org/Flask-Caching/)

**Docker configuration**: 3 CPUs, RAM 1024 MB

**Gunicorn configuration**:
- workers = 2*CPUs + 1 (recommended by doc)
- threads=1 (same behavior with 2*CPUs threads)
- worker_class="egg:meinheld#gunicorn_worker"

**Comment by jamadden** [comment] 2019-05-15 18:25
In https://github.com/benoitc/gunicorn/issues/2015 someone else had problems with a meinheld worker hanging, and using a different worker type solved the problem. I wonder if there's a general issue with it. @stapetro are you able to try a different worker?

**Comment by stapetro** [comment] 2019-05-16 14:22
Hello @jamadden ,
Your suggestion fixed the issue. There's no problem with both _gevent_ and _gthread_ worker classes. I moved away from meinheld. Thank you for the quick reply and help! :)

**Comment by mikkelhn** [comment] 2020-06-06 20:34
> Full STR:
> 
> 1. Create a free Heroku account at https://signup.heroku.com
> 2. Install the Heroku CLI (see https://devcenter.heroku.com/articles/heroku-cli)
> 3. Log into the CLI using `heroku login`
> 4. `git clone https://github.com/erjiang/gunicorn-issue && cd gunicorn-issue`
> 5. `heroku create` (this creates a free Heroku app with randomly generated name and configures a git remote named `heroku`)
> 6. `git push heroku master`
> 7. `curl --data "foo=bar" https://YOUR_GENERATED_APP_NAME.herokuapp.com/test1` (fails >75% of the time)
> 8. When finished, run `heroku destroy` to delete the app.

I had very similar behaviour on my app, and found that when using curl -H instead of curl --data (since it's a GET request) it works for my app (Django, Gunicorn, Heruko). I have not tested on the gunicorn-issue app. Thought this might be useful to someone.

**Comment by RinaldoNani** [comment] 2020-06-08 01:31
@mikkelhn Yesss. An app with Flask/Flask RestPlus and Gunicorn behaves in this way: replying to POST request gives 503 error [if payload > 13k], while the error **does not** happen if the app replies to a GET. Exactly the same code! 
Can anyone explain this very annoying behavior? Is switching to waitress the only workaround to fix this issue? I feel that modifying Gunicorn "by hand" is not a viable solution...

**Comment by erjiang** [comment] 2020-06-08 19:17
I went ahead and opened a PR to call shutdown() before close(). Frankly, it's a bit wild that Heroku continues to recommend Gunicorn when it's broken by default on Heroku.

**Comment by RinaldoNani** [comment] 2020-06-08 19:38
If, as @erijang correctly states, Heroku recommends Gunicorn when Gunicorn is not the way to go: which are simple and viable alternatives to Gunicorn (and how to best configure them on Heroku)?
AFAIK, many customers choose Heroku just because it should not require a deep knowledge in server architectures and configuration details... :|

**Comment by benoitc** [comment] 2020-06-08 19:40
@RinaldoNani what do you mean? Also which worker are we talking about? .

**Comment by edmorley** [comment] 2020-06-08 19:45
@benoitc This issue affects multiple worker types, as mentioned in:
https://github.com/benoitc/gunicorn/issues/840#issuecomment-482491267

**Comment by RinaldoNani** [comment] 2020-06-08 20:26
Hi @benoitc. As I mentioned in a previous post, we have deployed a pretty simple Flask / FalskRestPlus app on Heroku, following with care Heroku's **guidelines** for Python/Flask server side application deployment  (which, as I understand, **suggest the use Gunicorn sync "web" workers**). 

The behavior of our app reflects the title of this thread.

Tested locally, everything works fine, the app delivers 20k+ JSON with no problems; but when the app is deployed on Heroku, the 503 error issue becomes systematic: even with literally no traffic, the output is not delivered. 
As others pointed out, the logs show that at HTTP level everything seems ok (200 response code is logged). 
If the payload is less than 13k, then Heroku/Gunicorn respond to POSTs as expected.
We followed @mikkelhn idea of avoiding POST (?!?) endpoints and use GET instead, and this seems a (not very nice) way to tackle  the problem. 

We are not Gunicorn experts, and frankly we expected that our simple use case could work "out of the box". 
If you have any suggestions to help us out, we will be forever grateful :)

**Comment by erjiang** [comment] 2020-06-08 21:59
@RinaldoNani Shot in the dark... somewhere in your  request handler, try reading all of `request.data`. For example:

```
@route('/whatever')
def whatever_handler():
    str(request.data)
    return flask.jsonify(...)
```

Does that have any effect on your errors?

**Comment by Anshuldubey0602** [comment] 2021-04-19 07:24
I am writing this at 1:00AM after hustling with H18 issue for over 2 weeks now (couldn't wait to share). 

I am working with huge dataset and responding 18K to 20K records to plot. H18 came as a very random error. It would work fine sometimes, but would throw "Content-header length doesn't match" on all the browsers. I tried almost all the solutions discussed about this issue but didn't have any luck. There were 2 things I tried which worked finally:
1. Changed  the POST request to GET.
2. My data had NaN/Null values so I changed my model and provided a default value. (I think this solved the issue)
After this, I stopped getting this error. 
Hope this could help someone!

**Comment by Williano** [comment] 2021-09-04 18:01
Using waitress works and helps avoid this problem. This article is old(2014) but explains better why waitress is good.

https://blog.etianen.com/blog/2014/01/19/gunicorn-heroku-django/

https://stackoverflow.com/questions/61742013/heroku-h18-server-request-interrupted-error-sending-image-form-data-from-node

Hope it helps someone.

**Comment by benoitc** [comment] 2021-09-04 18:26
@Williano what would help is providing full log of what happening.

Looking at the example it seems to start to answer without reading the request body which is not appropriate. Others solution may work because they are ready the whole body before passing it to the application. Which is not the case of gunicorn. 

For large body it is recommanded to either use asynnc upload from nginx or similar or if you want to do it in Python to use an async woker. The most simplest one is the threaded one.

**Comment by Williano** [comment] 2021-09-04 21:57
Great. Thank you very much for the recommendation. I will look into that.

I am sorry if what I posted caused any problem.

**Comment by NoahCardoza** [comment] 2021-09-13 19:13
@RinaldoNani and @bencochran

In my case, there wasn't any type of POST body, it was a GET request. Should I still have tried to read the request body? 

In any case, I was just working on a quick weekend project so rather than debug it too deeply I ended up switching to [waitress](https://docs.pylonsproject.org/projects/waitress/en/latest/) which seems to be working fine. However, it's not a long-term solution and it's probably not the right idea unless you are working on a hackathon-type project like mine.

**Comment by benoitc** [comment] 2021-09-13 19:19
seriously please stop saying using waitress solves thus  issue. Did you try an async worker? did you try to actually read the body in your app or discard it if you don’t need it?

one of the diff is that the body is streamed ans nit fully read before the application callback is executed. Which is probably what triggering this error. If the app send without reading the body it Ill not work with gunicorn.

**Comment by edmorley** [comment] 2021-09-13 19:29
@benoitc If I'm understanding correctly, you're saying that at least for the testcase in the issue description, the issue is caused by an invalid app design, rather than an issue with gunicorn?

If that's the case, could you explain why adding the `.flush()` resolves the issue, as described here?
https://github.com/benoitc/gunicorn/issues/840#issuecomment-482491267

Also, if this is an invalid app design, is there a way that gunicorn could detect this case and fail with a clearer error message, so that app authors know that it's something they need to fix? (And so we can close this long running issue out once and for all?)

> Did you try an async worker?

I realise this question was directed at someone else, but I just wanted to check that you'd seen my reply here which confirms the issue reproduces with multiple worker types?
https://github.com/benoitc/gunicorn/issues/840#issuecomment-640848244

**Comment by erjiang** [comment] 2021-09-13 20:04
I think @benoitc could clarify things by explaining what the tradeoff is here and why gunicorn should not help the app handle any remaining unread data. For example, maybe there are significant performance or other advantages to be had that would not be possible if e.g. the above patch were applied.

**Comment by tilgovi** [comment] 2021-09-19 23:42
My understanding is that waitress buffers the full request body before invoking the application to handle the request. Gunicorn does not. This has the advantage that an application can stream the request body, perhaps processing a request body that is very large and should not be kept all in memory, or returning early and more quickly when there's a problem with the request, which makes Gunicorn able to handle some use cases that perhaps waitress would be inappropriate for. The disadvantage is that some reports in this thread indicate that failing to read the whole request body can cause these kinds of issues on Heroku.

If it does seem to be the case that reading the whole request body fixes the situation, then we should close this because I think Gunicorn is working as intended.

Issues that seem related but involve a GET request might perhaps be separate issues.

**Comment by korutarwebdeploy** [comment] 2021-12-06 04:02
I have ran in to this issue recent days, and I did read through the entire conversations to figure out what to do. Indeed, on one hand, the use of gunicorn brings rather speed experience, and that seems to be the new demand of web applications. On the other hand, real life application handles rather huge amount of data. 13k is something consider small.

So in fact, what I've decided was to patch handling between my Django and my JavaScript. Sorry that this suggestion may sound stupid, but I found this legit for me as a first year program coding learner. As my app does have a few steps to handle a few sets of huge amount of data. I pass each step to JavaScript and back and forth to Django. Assuring that each step within the function pass rather smaller set of data.

At the end of the day, that is my case using Heroku. Hope my suggestion here may give some light to anyone may be same

**Comment by edmorley** [comment] 2021-12-06 06:31
@benoitc Hi! Could you take a look at the questions here?
https://github.com/benoitc/gunicorn/issues/840#issuecomment-918509121

**Comment by benoitc** [comment] 2022-10-14 09:03
body should be read or discarded by the application.So if the application doesn't do anything with a request that is sending a body it will be an issue. Body has to be ready.  Gunicorn is very explicit in is way to maintain the http session and doesn't ready the body before the application ask for it, this reduce the memory usage.

**Comment by edmorley** [comment] 2022-10-14 10:04
@benoitc Thank you for replying. However that still doesn't answer all of my questions / counter-evidence from this comment (from September 2021):
https://github.com/benoitc/gunicorn/issues/840#issuecomment-918509121

Your reply suggests that the answer to my first question (`the issue is caused by an invalid app design, rather than an issue with gunicorn?`) is "yes". 

However, my findings here seem to contradict that (plus the question about whether there is anything to do to improve the UX here was unanswered):
https://github.com/benoitc/gunicorn/issues/840#issuecomment-482491267

Specifically if a call to `sock.shutdown(socket.SHUT_RDWR)` is added in gunicorn before the `sock.close()` (or even just a sleep), then the issue doesn't occur. 

Given `sock.shutdown` is specifically called out in the `sock.close()` docs, it seems that gunicorn may not be using that API correctly? 

Do you know of a reason why we shouldn't add the shutdown?

At the very least, perhaps gunicorn could detect the "body not read" case when connection closed case, and emit a warning to improve the UX?

**Comment by benoitc** [comment] 2023-05-07 18:21
let's close this issue and continue in #840. Heroku is different todaty.

**Comment by benoitc** [comment] 2023-05-07 18:22
let's close this issue and continue in #840. Heroku is different todaty.

**Comment by benoitc** [comment] 2024-08-06 16:13
heroku is gone.

**Closed by benoitc** 2024-08-06 16:13 UTC
Labels: bug :(, Feedback Requested, unconfirmed, help wanted, - Bugs -
