### ISSUE TITLE
Auto worker reboot  during concurrent test

### ISSUE THREAD

**Issue by karlosmid** [benoitc/gunicorn#1517] opened 2017-05-24 07:58 UTC
**Headline**

During the concurrent test, we have gunicorn worker auto reboot. There is no additional information in gunicorn log. gunicorn runs as docker container. In front of gunicorn, there is nginx that also runs in separated container.

**Environment**

OS:  3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

gunicorn: gunicorn (version 19.7.1)

nginx: nginx version: nginx/1.11.10

docker: Docker version 1.13.0, build 49bf474

```
 ulimit -n
65535
```

**docker compose file**

```
web:
  build: .
  restart: always
  command: gunicorn slweb.wsgi:application --bind :8000 --workers 8 --threads 8 -k gthread --timeout 120 --log-level=debug --error-logfile /app/logs/gunicorn.log --access-logfile /app/logs/gunicorn-access.log
  env_file: .env
  expose:
    - "8000"
  net: "host"
  volumes:
    - "/sl-data/certs:/etc/nginx/certs"
    - "/home/sl-web/schedulers/logs:/app/schedulers/logs"
    - "/home/sl-web/logs:/app/logs"
    - "/sl-data/integration_logs:/app/integration_logs"
    - "/sl-data/temp:/app/temp"
    - "/sl-data/certificates:/app/certificates"
    - "/mnt/sl_mic_share/integration_logs:/app/mic_integration_logs"



proxy:
  image: slwebbackend_proxy
  restart: always
  ports:
    - "80:8000"
  volumes:
    - "/sl-data/nginx_certs:/etc/nginx/certs"
    - "/var/run/docker.sock:/tmp/docker.sock"
    - "/home/sl-web/log/nginx:/var/log/nginx"
  net: "host"
```

**Steps**

1. gunicorn log content after gunicorn reboot command:

```
  max_requests: 0
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  accesslog: /app/logs/gunicorn-access.log
  daemon: False
  enable_stdio_inheritance: False
  do_handshake_on_connect: False
  max_requests_jitter: 0
  check_config: False
  worker_int: <function WorkerInt.worker_int at 0x7fa1f2b880d0>
  preload_app: False
  chdir: /app
  user: 1030
  umask: 0
  initgroups: False
  proxy_allow_ips: ['127.0.0.1']
  graceful_timeout: 30
  proc_name: None
  config: None
  errorlog: /app/logs/gunicorn.log
  logconfig: None
  on_starting: <function OnStarting.on_starting at 0x7fa1f2b806a8>
  on_reload: <function OnReload.on_reload at 0x7fa1f2b80840>
  when_ready: <function WhenReady.when_ready at 0x7fa1f2b809d8>
  pre_exec: <function PreExec.pre_exec at 0x7fa1f2b88400>
  pre_request: <function PreRequest.pre_request at 0x7fa1f2b88598>
  suppress_ragged_eofs: True
  bind: [':8000']
  workers: 8
  limit_request_fields: 100
  forwarded_allow_ips: ['127.0.0.1']
  ca_certs: None
  keepalive: 2
  ciphers: TLSv1
  syslog_addr: udp://localhost:514
  default_proc_name: slweb.wsgi:application
  statsd_host: None
  group: 1030
  raw_paste_global_conf: []
[2017-05-24 07:46:48 +0000] [1] [INFO] Starting gunicorn 19.7.1
[2017-05-24 07:46:48 +0000] [1] [DEBUG] Arbiter booted
[2017-05-24 07:46:48 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2017-05-24 07:46:48 +0000] [1] [INFO] Using worker: gthread
[2017-05-24 07:46:48 +0000] [7] [INFO] Booting worker with pid: 7
[2017-05-24 07:46:48 +0000] [9] [INFO] Booting worker with pid: 9
[2017-05-24 07:46:48 +0000] [10] [INFO] Booting worker with pid: 10
[2017-05-24 07:46:48 +0000] [12] [INFO] Booting worker with pid: 12
[2017-05-24 07:46:48 +0000] [14] [INFO] Booting worker with pid: 14
[2017-05-24 07:46:48 +0000] [15] [INFO] Booting worker with pid: 15
[2017-05-24 07:46:49 +0000] [17] [INFO] Booting worker with pid: 17
[2017-05-24 07:46:49 +0000] [18] [INFO] Booting worker with pid: 18
[2017-05-24 07:46:49 +0000] [1] [DEBUG] 8 workers
[2017-05-24 07:47:00 +0000] [9] [DEBUG] HEAD /
[2017-05-24 07:47:00 +0000] [9] [DEBUG] Closing connection.
[2017-05-24 07:47:05 +0000] [9] [DEBUG] HEAD /
[2017-05-24 07:47:05 +0000] [9] [DEBUG] Closing connection.
[2017-05-24 07:47:10 +0000] [9] [DEBUG] HEAD /
[2017-05-24 07:47:10 +0000] [9] [DEBUG] Closing connection.
```

2. we use blitzy tool for generating load on REST api: https://github.com/karlosmid/blitzy

3. Problematic request is POST request that takes ~3s

4. Here is gunicorn log for 5 concurrent requests.

```
Total requests    : 5
Total workers    : 5
Successful reqs  : 1
Failed reqs      : 4
Average (msecs)  : 1778.0
Longest (msecs)  : 1778.0
Shortest (msecs) : 1778.0
RPS (secs)       : 5.0e3
```

```
[2017-05-24 07:52:46 +0000] [9] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:52:46 +0000] [17] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:52:46 +0000] [9] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:52:46 +0000] [9] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:52:46 +0000] [9] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:52:46 +0000] [90] [INFO] Booting worker with pid: 90
[2017-05-24 07:52:47 +0000] [17] [DEBUG] Closing connection.
```

**Question**

We we have worker boot?

3. second run:

```
Total requests    : 5
Total workers    : 5
Successful reqs  : 5
Failed reqs      : 0
Average (msecs)  : 2355.6
Longest (msecs)  : 2434.0
Shortest (msecs) : 2168.0
RPS (secs)       : 5.0e3
```

```

[2017-05-24 07:56:12 +0000] [90] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:56:12 +0000] [12] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:56:12 +0000] [10] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:56:12 +0000] [7] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:56:12 +0000] [14] [DEBUG] POST /slsync/synchronize
[2017-05-24 07:56:14 +0000] [14] [DEBUG] Closing connection.
[2017-05-24 07:56:14 +0000] [7] [DEBUG] Closing connection.
[2017-05-24 07:56:14 +0000] [90] [DEBUG] Closing connection.
[2017-05-24 07:56:14 +0000] [10] [DEBUG] Closing connection.
[2017-05-24 07:56:14 +0000] [12] [DEBUG] Closing connection.
```

**Info**

There is no reboot. We have non deterministic behavior for gunicorn worker reboot.

**Comment by tilgovi** [comment] 2017-07-11 00:37
Thank you for such a detailed issue report. Unfortunately, I am unable to understand what behavior you expect. My best guess is that you're not expecting a worker to restart, but it does. Is that correct?

**Comment by karlosmid** [comment] 2017-07-11 05:27
Hi @tilgovi , yes, the question is why worker restarts? In log there is no any exception.
I am interesting why worker restarts, because produced load is not so big.

**Comment by tilgovi** [comment] 2017-07-11 06:14
Is it possible there's a memory limit on the container and this causes processes to be killed when there's too much concurrency?

**Comment by karlosmid** [comment] 2017-07-11 06:33
Hm, but then, there should be Python OutOfMemory exception. But log is empty. When do you call worker restart? Triggered on unix signals?

**Comment by tilgovi** [comment] 2017-07-17 00:10
I would expect to see an exception in the log if the worker caught a problem. That is why I suspect it could be exiting unexpectedly. In that case, the arbiter would just start a new one.

Workers are only restarted when there are fewer than requested alive. `--max-requests`, an explicit reload signal (like `SIGHUP`) or when a worker crashes.

**Comment by benoitc** [comment] 2017-08-31 04:02
to the list i would also add "when the the worker is kept busy too long". 

I don't understand the last line:

>Info
> 
> There is no reboot. We have non deterministic behavior for gunicorn worker reboot.

what do you mean? You don't always reproduce the behaviour?

How are you using the `blitzy` tool?

**Comment by karlosmid** [comment] 2017-08-31 15:56
@benoitc  about the info: I stated that in second test with 5 concurrent threads, there was no reboot.
Yes, we have the case when backend takes time to calculate response.

We have not managed to correlate gunicorn timeout parameters with actual reboot.

You stated that:
```when the the worker is kept busy too long```

How much is too long?

Blitzy is run from one laptop (same ip address) running concurrent erlang threads. Each thread is making http request.

**Comment by KumarManoj-S** [comment] 2021-01-29 06:49
Hi @karlosmid, were you able to fix this issue? I'm facing the same issue but no clue what is happening?!

**Comment by karlosmid** [comment] 2021-01-29 07:42
Hi @KumarManoj-S, we were not able to figure it out. I will ask my college that continued working on that project. Do you have the latest unicorn and long lasting requests?

**Comment by benoitc** [comment] 2022-10-14 08:39
sounds like the application is preventing the worker to notify the arbiter in time. I am closing it, since it's a long time anyway.

**Closed by benoitc** 2022-10-14 08:39 UTC
