### ISSUE TITLE
--cert-reqs 1 doesn't really work

### ISSUE THREAD

**Issue by varunarora** [benoitc/gunicorn#1532] opened 2017-06-20 08:35 UTC
I wish to run Gunicorn both for SSL and non-SSL requests, behind an Nginx proxy.

The problem is that the following statement doesn't work for non-SSL requests:

    gunicorn ... --cert-reqs 1 --keyfile /etc/ssl/private/privkey.pem --certfile /etc/ssl/certs/cert.pem

It generates a `[SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure` on non-SSL requests. Even though `1` should make the SSL part optional.

I feel like the problem is coming from the `is_ssl` property being defined from the config's `keyfile` or `certfile` params, as this is being used as a basis for scheme of request instead of allowing either. Removing these altogether gives `SSL Handshake` errors with Nginx, which doesn't work either.

At this point, I am just planning to run two processes, one with the SSL params and one without, on different ports.

Thank you for your help in resolving this issue.

**Comment by varunarora** [comment] 2017-06-20 08:49
Oh wait - I can't figure out how to run two different gunicorn processes. So I am back to trying to fix this :(

**Comment by varunarora** [comment] 2017-06-21 09:29
Running the following until this is patched or there is a more elegant solution:

    sed -i "s/if self.cfg.is_ssl/if self.cfg.is_ssl and ('cert_reqs' in self.cfg.ssl_options and self.cfg.ssl_options['cert_reqs'] == 1 and client.getsockname()[1] == 443)/" /usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py && \
    sed -i "s/if self.cfg.is_ssl/if self.cfg.is_ssl and ('cert_reqs\' in self.cfg.ssl_options and self.cfg.ssl_options['cert_reqs'] == 1 and self.sock.getsockname()[1] == 443)/" /usr/local/lib/python2.7/dist-packages/gunicorn/workers/gthread.py && \
    sed -i "s/if self.cfg.is_ssl/if self.cfg.is_ssl and ('cert_reqs' in self.cfg.ssl_options and self.cfg.ssl_options['cert_reqs'] == 1 and client.getsockname()[1] == 443)/" /usr/local/lib/python2.7/dist-packages/gunicorn/workers/geventlet.py && \
    sed -i "s/if self.cfg.is_ssl/if self.cfg.is_ssl and ('cert_reqs' in self.cfg.ssl_options and self.cfg.ssl_options['cert_reqs'] == 1 and len(self.sockets) > 0 and self.sockets[0].getsockname()[1] == 443)/" /usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py

**Comment by berkerpeksag** [comment] 2017-06-21 13:30
Thank you for the report. I know this isn't a direct answer to your question, but since you are going to use nginx, you could handle SSL configuration in your nginx configuration. Is there a particular reason why do you want to set SSL settings in Gunicorn?

**Comment by varunarora** [comment] 2017-06-22 02:51
@berkerpeksag Handshake was failing between Gunicorn and Nginx when SSL was only configured at the Nginx layer.

**Comment by berkerpeksag** [comment] 2017-07-13 23:55
> At this point, I am just planning to run two processes, one with the SSL params and one without, on different ports.

Unfortunately, there is no way to serve both HTTP and HTTPS requests in the same Gunicorn instance at the moment. There is already an open issue about supporting it in #1466. I'm closing this as a duplicate of #1466, but feel free to ping us if you think otherwise. Thank you for the report again!

**Closed by berkerpeksag** 2017-07-13 23:55 UTC

**Comment by varunarora** [comment] 2017-07-16 21:14
Makes sense - thanks. Just fyi, I have been using my changes pasted in the earlier comment to where `is_ssl` is checked for, and it works well for now on my production workload.
