### ISSUE TITLE
No error output produced if module level exception raised in django app

### ISSUE THREAD

**Issue by augonis** [benoitc/gunicorn#987] opened 2015-02-24 07:39 UTC
I have a django app that runs fine with *manage.py runserver*, but if I start the same app with *gunicorn app.wsgi:appliacation* and it returns 500 response on all urls and it's not the 500 configured in django. My main gripe is the no output thing as that seriously hinders looking for the real error. So I added a known point of failure (an impossible import in urlconf) to find anywhere that would say " ImportError: No module named 'something' ", but nothing, either it's not outputted anywhere or I just can't find it.

Any ideas?

**Comment by tilgovi** [comment] 2015-02-24 18:59
I don't think I understand the issue exactly, and maybe the additional thing you tried with the `ImportError` is actually confusing me.

I thought, when I first started reading, that this was about either exception logging or error pages, both of which may just be configuration that needs to be changed. However, the last part about `ImportError` should cause some logging since gunicorn workers should fail to start if the application cannot make any import. Of course, I don't know enough about Django to guess, but if the URL map is imported later, and not as part of the initial import of `app.wsgi` module, then this could again be an issue with gunicorn or Django logging configurations.

Can you understand my confusion? Can you offer a bit more detail or provide some example code and a description of what you expect vs what you see?

**Comment by augonis** [comment] 2015-02-25 07:11
Here is what I have in one of my urlconfs:
```python
from django.conf.urls import patterns, url
urlpatterns = patterns('',
   #........
)
print('impossible')
import something # point of failure
print('import')
```
When I start django development server with `python manage.py runserver` in the console I get this
```
Validating models...

0 errors found
February 25, 2015 - 08:27:26
Django version 1.6.5, using settings 'pro.settings'
Starting development server at http://0.0.0.0:8021/
Quit the server with CONTROL-C.
# server has started I send request
impossible #print from the urlconf
Traceback (most recent call last):
  File "/www/ts/env/lib/python3.3/site-packages/django/core/urlresolvers.py", line 358, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  # ..........
  File "/www/rep/workOrder/urls.py", line 15, in <module>
    import something
ImportError: No module named 'something'
[25/Feb/2015 08:37:14] "GET / HTTP/1.1" 500 59
impossible  #print from the urlconf
Traceback (most recent call last):
  File "/www/ts/env/lib/python3.3/site-packages/django/core/urlresolvers.py", line 358, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  # ...........
  File "/www/rep/workOrder/urls.py", line 15, in <module>
    import something
ImportError: No module named 'something'
```
From this I can tell that server starts fine and on first request django tries to import urlconf twice failing both times.

Running gunicorn with `gunicorn -b 0.0.0.0:8021  pro.wsgi:application` in the console I get this
```
[2015-02-25 08:57:39 +0200] [27286] [INFO] Starting gunicorn 19.2.1
[2015-02-25 08:57:39 +0200] [27286] [INFO] Listening at: http://0.0.0.0:8021 (27286)
[2015-02-25 08:57:39 +0200] [27286] [INFO] Using worker: sync
[2015-02-25 08:57:39 +0200] [27289] [INFO] Booting worker with pid: 27289
# server has started I send request
impossible  #print from the urlconf
impossible  #print from the urlconf
```
We see the two attempts to import urlconf, but no traceback anywhere.

The pages shown in the browser also are different on both servers, neither being what's configured in django. This suggests that such errors are handled at server level rather than framework.

**Comment by benoitc** [comment] 2015-03-06 07:54
what if you run in debug level?

**Comment by augonis** [comment] 2015-03-08 06:23
if You mean  `gunicorn -b 0.0.0.0:8021 --log-level=debug pro.wsgi:application`, then  only extra output is the url called.

**Comment by benoitc** [comment] 2015-03-09 06:18
On Sunday, March 8, 2015, augonis <notifications@github.com> wrote:

> if You mean gunicorn -b 0.0.0.0:8021 --log-level=debug
> pro.wsgi:application, then only extra output is the url called.
>
>
>
do you have a sample code that could help to reproduce the issue?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benoitc/gunicorn/issues/987#issuecomment-77735502>.
>


-- 
Sent from my Mobile

**Comment by augonis** [comment] 2015-03-10 06:41
Sorry, false alarm. I wasn't able to replicate symptoms on a fresh django project, so it must be something with my django configuration.

**Comment by benoitc** [comment] 2015-04-01 09:17
ok  thanks, closing the issue then

**Closed by benoitc** 2015-04-01 09:17 UTC
Labels: Feedback Requested
