### ISSUE TITLE
OSError: [Errno 107] Socket not connected when having multiple short healthchecks

### ISSUE THREAD

**Issue by jacek-jablonski** [benoitc/gunicorn#2070] opened 2019-07-01 11:28 UTC
Hi,
I am running dockerized application with gunicorn. I noticed that I'm having multiple OSError messages, when gunicorn is trying to parse headers and socket is in not connected state:
```
OSError: [Errno 107] Socket not connected
  File "gunicorn/workers/sync.py", line 134, in handle
    req = six.next(parser)
  File "gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "gunicorn/http/message.py", line 230, in parse
    self.headers = self.parse_headers(data[:idx])
  File "gunicorn/http/message.py", line 74, in parse_headers
    remote_addr = self.unreader.sock.getpeername()
```
context:
```
data = b'Connection: close'
headers = []
```
gunicorn.py.ini:
```
import os

bind = os.environ.get('GUNICORN_BIND', '0.0.0.0:' + os.environ.get('PORT', '8000'))
workers = os.environ.get('GUNICORN_WORKERS', 8)
accesslog = None
errorlog = '-'
loglevel = os.environ.get('GUNICORN_LOGLEVEL', '')
user = os.environ.get('GUNICORN_USER', 'root')
group = os.environ.get('GUNICORN_GROUP', 'root')
```

Is it something wrong with my configuration?

**Comment by benoitc** [comment] 2019-07-03 15:06
what does your request?

**Comment by jacek-jablonski** [comment] 2019-07-03 18:32
It's a healthcheck.

**Comment by cbrintnall** [comment] 2019-08-15 17:28
This sounds related to #2078. I imagine 2078 is also attempting to read after the socket has closed.

**Comment by benoitc** [comment] 2019-11-22 14:53
duplicate of #2078

**Closed** 2022-06-02 07:08 UTC
Labels: bug :(, Feature/Http
