### ISSUE TITLE
Gunicorn Worker failed to boot on project.py

### ISSUE THREAD

**Issue by zhangdongasia** [benoitc/gunicorn#2311] opened 2020-04-17 14:01 UTC
```python
# myproject.py
import base64
import json
import os
import uuid
import flask

from flask import (
    Flask,
    Response,
    request,
    redirect,
    make_response,
    url_for,
    abort,
)

app = flask.Flask(__name__)

@app.route("/")
def index():
    headers = flask.request.headers
    return "Request headers:\n" + str(headers)

app.run(host="0.0.0.0")
```
```console
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$ python3.6 myproject.py
 * Serving Flask app "myproject" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [17/Apr/2020 01:25:04] "GET / HTTP/1.1" 200 -
^C(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
```

```python
# wsgi.py
from myproject import app # BUT THIS ALREADY CALLS app.run()!!!

if __name__ == "__main__":
    app.run()
```
```console
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$ cd ~/myproject ; gunicorn --bind 0.0.0.0:5000 wsgi:app
[2020-04-17 01:25:44 +0000] [4009] [INFO] Starting gunicorn 20.0.4
[2020-04-17 01:25:44 +0000] [4009] [INFO] Listening at: http://0.0.0.0:5000 (4009)
[2020-04-17 01:25:44 +0000] [4009] [INFO] Using worker: sync
[2020-04-17 01:25:44 +0000] [4012] [INFO] Booting worker with pid: 4012
 * Serving Flask app "myproject" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2020-04-17 01:25:44 +0000] [4012] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/myproject/wsgi.py", line 1, in <module>
    from myproject import app
  File "/home/ubuntu/myproject/myproject.py", line 29, in <module>
    app.run(host="0.0.0.0")
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/ubuntu/myproject/myprojectenv/lib/python3.6/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
[2020-04-17 01:25:44 +0000] [4012] [INFO] Worker exiting (pid: 4012)
[2020-04-17 01:25:44 +0000] [4009] [INFO] Shutting down: Master
[2020-04-17 01:25:44 +0000] [4009] [INFO] Reason: Worker failed to boot.
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
```
However, under identical/same circumstance, if gunicorn bind a "STATIC" myproject.py, it's working well …

```python
# myproject.py, second example
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "<h1 style='color:blue'>Hello There!</h1>"

if __name__ == "__main__":
    app.run(host='0.0.0.0')
```
```console
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$ python3.6 myproject.py
 * Serving Flask app "myproject" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [17/Apr/2020 01:50:04] "GET / HTTP/1.1" 200 -
^C(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$ gunicorn --bind 0.0.0.0:5000 wsgi:app
[2020-04-17 01:27:05 +0000] [4062] [INFO] Starting gunicorn 20.0.4
[2020-04-17 01:27:05 +0000] [4062] [INFO] Listening at: http://0.0.0.0:5000 (4062)
[2020-04-17 01:27:05 +0000] [4062] [INFO] Using worker: sync
[2020-04-17 01:27:05 +0000] [4065] [INFO] Booting worker with pid: 4065
^C[2020-04-17 01:27:21 +0000] [4062] [INFO] Handling signal: int
[2020-04-17 01:27:21 +0000] [4065] [INFO] Worker exiting (pid: 4065)
[2020-04-17 01:27:21 +0000] [4062] [INFO] Shutting down: Master
(myprojectenv) ubuntu@ip-20-0-2-37:~/myproject$
```

**Comment by benoitc** [comment] 2020-04-17 14:02
what is your issue?

**Comment by jamadden** [comment] 2020-04-17 14:10
I've cleaned up the formatting.

The error is `OSError: [Errno 98] Address already in use`

And the cause is clear: You're trying to have both gunicorn and the built-in flask server run the app (because you're calling `app.run` at module scope in `myproject.py`). Pick one or the other.

**Comment by jamadden** [comment] 2020-04-17 14:10
Closed as a duplicate of #2309

**Comment by benoitc** [comment] 2020-04-17 14:11
@jamadden thanks :)

**Closed by jamadden** 2020-04-17 14:10 UTC

**Comment by zhangdongasia** [comment] 2020-04-17 15:12
@jamadden thanks :)
