### ISSUE TITLE
Gunicorn fails to send wsgi app exceptions with gevent worker class 

### ISSUE THREAD

**Issue by Lothiraldan** [benoitc/gunicorn#1282] opened 2016-05-24 17:47 UTC
In some cases, we raise an exception in our wsgi app and in this case we get an empty response.

Here is a minimal reproductible wsgi application:

```
def app(arg, arg2):
    1/0
```

When running gunicorn with gevent worker like this:

```
gunicorn -k gevent --access-logfile - --error-logfile - --log-level debug wsgi:app
```

I get this log:

```
[2016-05-24 19:37:12 +0200] [16003] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x107cf71b8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: gevent
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x107cede60>
  pre_fork: <function pre_fork at 0x107cf7050>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: -
  group: 20
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x107cedcf8>
  pre_exec: <function pre_exec at 0x107cf7758>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x107cf7320>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x107cf7de8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x107cf78c0>
  post_request: <function post_request at 0x107cf79b0>
  user: 501
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x107cf7488>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x107cf7b18>
  chdir: /tmp
  paste: None
  default_proc_name: wsgi:app
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: unix:///var/run/syslog
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x107cedb90>
  worker_abort: <function worker_abort at 0x107cf75f0>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x107cf7c80>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix:
[2016-05-24 19:37:12 +0200] [16003] [INFO] Starting gunicorn 19.4.5
[2016-05-24 19:37:12 +0200] [16003] [DEBUG] Arbiter booted
[2016-05-24 19:37:12 +0200] [16003] [INFO] Listening at: http://127.0.0.1:8000 (16003)
[2016-05-24 19:37:12 +0200] [16003] [INFO] Using worker: gevent
[2016-05-24 19:37:12 +0200] [16006] [INFO] Booting worker with pid: 16006
[2016-05-24 19:37:12 +0200] [16003] [DEBUG] 1 workers
[2016-05-24 19:37:22 +0200] [16006] [DEBUG] GET /
[2016-05-24 19:37:22 +0200] [16006] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/Users/lothiraldan/.virtualenvs/sqreen/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/Users/lothiraldan/.virtualenvs/sqreen/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 163, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/Users/lothiraldan/.virtualenvs/sqreen/lib/python2.7/site-packages/gunicorn/workers/async.py", line 105, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/tmp/wsgi.py", line 5, in app
    1/0
ZeroDivisionError: integer division or modulo by zero
127.0.0.1 - - [24/May/2016:19:37:22 +0200] "GET / HTTP/1.1" 500 - "-" "-"
[2016-05-24 19:37:22 +0200] [16006] [DEBUG] Failed to send error message.
[2016-05-24 19:39:26 +0200] [16003] [INFO] Handling signal: winch
[2016-05-24 19:39:26 +0200] [16003] [DEBUG] SIGWINCH ignored. Not daemonized

[2016-05-24 19:39:51 +0200] [16003] [INFO] Handling signal: winch
[2016-05-24 19:39:51 +0200] [16003] [DEBUG] SIGWINCH ignored. Not daemonized
^C[2016-05-24 19:39:52 +0200] [16003] [INFO] Handling signal: int
[2016-05-24 19:39:52 +0200] [16006] [INFO] Worker exiting (pid: 16006)
[2016-05-24 19:39:52 +0200] [16003] [INFO] Shutting down: Master
```

And curl tell me that he gets an empty response:

```
curl http://localhost:8000
curl: (52) Empty reply from server
```

Running the same wsgi application with the sync worker correctly send me back a 500 html page.

Here are the relevant versions of packages in my environment:

 * gunicorn==19.4.5
 * gevent==1.1.0

I tried to dig up a little and I get this traceback that gives more clues:

```
[2016-05-24 18:12:28 +0200] [12867] [DEBUG] Failed to send error message.
Traceback (most recent call last):
  File "/Users/lothiraldan/.virtualenvs/AgentPythonTests/lib/python2.7/site-packages/gunicorn/workers/base.py", line 254, in handle_error
    util.write_error(client, status_int, reason, mesg)
  File "/Users/lothiraldan/.virtualenvs/AgentPythonTests/lib/python2.7/site-packages/gunicorn/util.py", line 345, in write_error
    write_nonblock(sock, http.encode('latin1'))
  File "/Users/lothiraldan/.virtualenvs/AgentPythonTests/lib/python2.7/site-packages/gunicorn/util.py", line 312, in write_nonblock
    return write(sock, data, chunked)
  File "/Users/lothiraldan/.virtualenvs/AgentPythonTests/lib/python2.7/site-packages/gunicorn/util.py", line 302, in write
    sock.sendall(data)
  File "/Users/lothiraldan/.virtualenvs/AgentPythonTests/lib/python2.7/site-packages/gevent/_socket2.py", line 412, in sendall
    timeleft = self.__send_chunk(chunk, flags, timeleft, end)
  File "/Users/lothiraldan/.virtualenvs/AgentPythonTests/lib/python2.7/site-packages/gevent/_socket2.py", line 357, in __send_chunk
    raise timeout('timed out')
timeout: timed out
```

From what I saw, https://github.com/gevent/gevent/blob/master/src/gevent/_socket2.py#L336 get called with a timeleft of `0.0` and in this case it seems that no data at all it sent as it check timeleft before trying to send a chunk.

I hope I gave enough informations, don't hesitate to ask for more if needed.

**Comment by jamadden** [comment] 2016-05-24 19:01
This potentially looks like a bug in gevent to me.

**Comment by jamadden** [comment] 2016-05-25 15:14
I've confirmed an issue in gevent and committed fixes.

**Comment by Lothiraldan** [comment] 2016-05-25 15:50
@jamadden Thank you I was not sure if it was a gevent bug or a gunicorn-gevent interaction bug

**Comment by berkerpeksag** [comment] 2016-05-25 16:14
Thanks @jamadden! Also thanks for the report @Lothiraldan. Closing this as 'fixed' now.

**Closed by berkerpeksag** 2016-05-25 16:14 UTC
