### ISSUE TITLE
Ignoring RootLogger while doing reopen_files

### ISSUE THREAD

**Issue by rocknrollnerd** [benoitc/gunicorn#1427] opened 2017-01-09 11:03 UTC
Hi!

I've encountered what seems to be the instance of the [old logrotate bug](https://github.com/benoitc/gunicorn/issues/345) when despite of sending USR1-signal correctly after rotating gunicorn still continues to log to the old logfile. However, the issue seemed to occur with root (top-level) logger only.

My logging config looks somewhat like this:

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file_root': {
                'class': 'logging.FileHandler',
                'filename': '/var/log/myproject/main.log'
            },
            'file_a': {
                'class': 'logging.FileHandler',
                'filename': '/var/log/myproject/a.log'
            },
            'file_b': {
                'class': 'logging.FileHandler',
                'filename': '/var/log/myproject/b.log'
            },
        },
        'loggers': {
            '': {
                'level': logging.INFO,
                'handlers': ['file_root']
            },
            'a': {
                'level': 'INFO',
                'handlers': ['file_a']
            },
            'b': {
                'level': 'INFO',
                'handlers': ['file_b']
            },
        }
    }

`a` and `b` loggers are rotated correctly, however `''` (root) logger is not.

This seems to happen because [loggers() function](https://github.com/benoitc/gunicorn/blob/2b839ca14437c61780d6eaaa8b24ad31e021f2c6/gunicorn/glogging.py#L90) only returns child loggers, ignoring root logger itself. Could that be fixed just by adding something like `return [logging.getLogger(name) for name in existing] + [root]`?

Thanks.

**Comment by f3anaro** [comment] 2017-03-08 12:39
I can confirm this bug. We run `gunicorn` in a Docker container with the following configs

`/app/config/gunicorn.py`:
```python
#
# Gunicorn Settings
#
worker_class = 'aiohttp.worker.GunicornWebWorker'

bind = '0.0.0.0:5000'

pid = '/run/gunicorn.pid'

# @see https://github.com/KeepSafe/aiohttp/issues/705
access_log_format = '%a %l %u %t "%r" %s %b'

# Number of web worker processes that should be spawned
workers = 4

# Log to stdout / stderr
accesslog = '/app/logs/gunicorn/access.log'
errorlog  = '/app/logs/gunicorn/error.log'
```

`/etc/logrotate.d/gunicorn`:
```logrotate
/app/logs/gunicorn/*.log {
    daily
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    create 640 root root
    sharedscripts
    postrotate
        [ ! -f /run/gunicorn.pid ] || kill -USR1 `cat /run/gunicorn.pid`
    endscript
}
```

`/app/logs/gunicorn/access.log.1` and `app/logs/gunicorn/error.log.1` are correctly moved, but `gunicorn` still writes into this files.

**Comment by tuukkamustonen** [comment] 2017-03-16 11:09
Is this a duplicate of https://github.com/benoitc/gunicorn/issues/1317?

I am using gunicorn 19.6.0 and can't reproduce this, but then, I don't provide custom `--log-config` anyway. Does it reproduce only when you do? I configure logging within (at the start of) my WSGI application. In gunicorn configs I just:

```
accesslog = '...'
access_log_format = '...'
errorlog = '...'
loglevel = 'info'
```

And I send `-USR1` by a harsh `killall` instead of by PID (until I have time to improve that).

**Closed** 2024-08-06 14:24 UTC
Labels: Feature/Logging, To Review
