### ISSUE TITLE
Gunicorn can't run in virtualenv on Win7

### ISSUE THREAD

**Issue by DJviolin** [benoitc/gunicorn#1005] opened 2015-04-09 20:42 UTC
I got the following error on Win7 when I try to run the gunicorn server inside virtualenv:

    $ (myappvenv) C:\www\python\myapp> gunicorn -b 0.0.0.0:8080 wsgi
    Traceback (most recent call last):
    File "C:\Python34\Lib\runpy.py", line 170, in _runmoduleasmain
    "main", modspec)
    File "C:\Python34\Lib\runpy.py", line 85, in _runcode
    exec(code, runglobals)
    File "C:\www\python\myapp\myappvenv\Scripts\gunicorn.exe_main.py", line 5, in <module>
    File "C:\www\python\myapp\myappvenv\lib\site-packages\gunicorn\app\wsgiapp.py", line 10, in <module>
    from gunicorn.app.base import Application
    File "C:\www\python\myapp\myappvenv\lib\site-packages\gunicorn\app\base.py", line 12, in <module>
    from gunicorn import util
    File "C:\www\python\myapp\myappvenv\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl
    ImportError: No module named 'fcntl'

My wsgi.py file looks like this:

    def application(env, start_response):
        start_response('200 OK', [('Content-Type', 'text/html')])
        return ["Hello!"]

Using the wsgi file from the Gunicorn readthedocs site also not helping, throwing the same error:

    def app(environ, start_response):
        """Simplest possible application object"""
        data = 'Hello, World!\n'
        status = '200 OK'
        response_headers = [
            ('Content-type','text/plain'),
            ('Content-Length', str(len(data)))
        ]
        start_response(status, response_headers)
        return iter([data])

Pip versions inside virtualenv:

    $ (my_app_venv) C:\www\python\my_app> pip list
    gunicorn (19.3.0)
    pip (6.1.1)
    setuptools (15.0)

Pip versions globally:

    $ C:\www\python\my_app> pip list
    pbr (0.10.8)
    pip (6.1.1)
    setuptools (15.0)
    six (1.9.0)
    stevedore (1.3.0)
    virtualenv (12.1.1)
    virtualenv-clone (0.2.5)
    virtualenvwrapper (4.3.2)

Python version: 3.4.3

**Comment by berkerpeksag** [comment] 2015-04-09 21:13
Thanks for the report. I'm not a Windows user, but I think Gunicorn does not support Windows yet. See #524.

**Comment by berkerpeksag** [comment] 2015-05-12 06:05
Closing this as a duplicate of #524.

**Closed by berkerpeksag** 2015-05-12 06:05 UTC
