### ISSUE TITLE
500 internal error ONLY when running gunicorn as a service

### ISSUE THREAD

**Issue by rivf** [benoitc/gunicorn#1059] opened 2015-06-30 02:33 UTC
Hello, guys. Don't know what's wrong.
I am using default digital ocean setup. I've used it a lot of times by now. But this time I needed to implement post request from my client mobile app. I've installed cors-headers app for django and tested my app locally for a long time, everything was great (btw my mobile app is written on ionic framework and uses angularjs to post). On server everything was also ok with following commands:
 python manage.py runserver 9000
and (!!!)
gunicorn config.wsgi --bind 127.0.0.1:9000
By ok I mean post requests were handled as they should be.  
But when I run gunicorn as a service (sudo service gunicorn restart) on every post request from my mobile app I get 500 internal server error. And this is just after everything was ok not in service mode. What's so different in service mode so it doesn't allow my post requests to reach server?
Again: the difference is only service / not service mode of gunicorn. (but of cource service mode has it's config while "working" gunicorn is just "gunicorn config.wsgi --bind 127.0.0.1:9000")

Also I need to say that the website is running fine even in service mode. So the problem is only with this cross-domain post requests.

Errors examples (gunicorn as a service): 
```
178.140.183.40 - - [29/Jun/2015:22:07:10 -0400] "POST /create_o_action/ HTTP/1.1" 500 58581 "-" "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
178.140.183.40 - - [29/Jun/2015:22:07:10 -0400] "POST /create_o_action/ HTTP/1.1" 500 58595 "-" "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
```

Success examples (gunicorn config.wsgi --bind 127.0.0.1:9000 ):
```
178.140.183.40 - - [29/Jun/2015:22:25:58 -0400] "POST /create_o_action/ HTTP/1.1" 200 32 "-" "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
178.140.183.40 - - [29/Jun/2015:22:25:58 -0400] "POST /create_c_action/ HTTP/1.1" 200 34 "-" "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36"
```

My gunicorn settings (more or less default digital ocean):

/etc/init/gunicorn.conf
```
description "Gunicorn daemon for Django project"

start on (local-filesystems and net-device-up IFACE=eth0)
stop on runlevel [!12345]

# If the process quits unexpectadly trigger a respawn
respawn

setuid django
setgid django
chdir /home/django/counter_platform_django

exec gunicorn \
    --name=webapp \
    --pythonpath=webapp \
    --bind=127.0.0.1:9000 \
    --config /etc/gunicorn.d/gunicorn.py \
    config.wsgi:application
```

 /etc/gunicorn.d/gunicorn.py
```
"""gunicorn WSGI server configuration."""
from multiprocessing import cpu_count
from os import environ


def max_workers():
    return cpu_count() * 2 + 1

max_requests = 1000
worker_class = 'gevent'
workers = max_workers()
```

So what's exactly different in two ways of running gunicorn? I'm really curious. Of course there is --daemon (which btw also works fine), but solution will be better.
Also I found a lot of questions on the internet (all without answers) about problems with post requests and gunicorn in service mode. If we will find solution - some of them also can be answered.

**Comment by wong2** [comment] 2015-07-01 09:49
is there any tracebacks while getting 500 error?

**Comment by benoitc** [comment] 2015-07-08 19:27
ther should be when log level is debug.

**Comment by benoitc** [comment] 2015-07-15 08:43
did you go further? Anything I can help?

**Comment by benoitc** [comment] 2015-07-24 08:00
@rivf ping.

**Comment by benoitc** [comment] 2015-09-08 12:00
WON'T FIX. the issue is not reproduced and no feedback from the original reporter to help us to reproduce it. Feel free to reopen it if you have more details.

**Closed by benoitc** 2015-09-08 12:00 UTC

**Comment by fjcaro** [comment] 2016-05-30 18:58
hey guys, i got this exact same situation, can this issue be reopened?

**Comment by benoitc** [comment] 2016-05-30 19:34
@fjcaro Sure but please create a new ticket linked to this one. If you have any more details, logs in debug mode or a way to reproduce it easily this is more than welcome :)

**Comment by asmyshlyaev177** [comment] 2017-02-01 04:47
Same situation and no answer. Uwsgi acts same way by the way.

**Comment by benoitc** [comment] 2017-02-01 05:33
@asmyshlyaev177 same answer as above... Please open a *new* tickets with a way to reproduce it and some logging. Will be happy to investigate the issue.
