### ISSUE TITLE
workertmp -> notify -> os.fchmod performance problem

### ISSUE THREAD

**Issue by fillest** [benoitc/gunicorn#1305] opened 2016-07-07 14:23 UTC
Hello.
We're currently trying to run our web app on gunicorn under tens of thousands requests/second of live traffic on AWS. A fast sampling profiler is continuosly enabled in production so I can check out the monitoring graphs and correlate the problematic moments with the profiler per-second reports. Basically, it shows top N stack traces which were most often sampled during a second.
Periodically I see something like this (percentage varies, e.g. it may be 18%) in the log:

```
30.3% gunicorn/workers/workertmp.py notify:43 'os.fchmod(self._tmp.fileno(), self.spinner)'
      <-  gunicorn/workers/base.py notify:70
      <-  gunicorn/workers/sync.py run_for_one:59
      <-  gunicorn/workers/sync.py run:122 
      <-  gunicorn/workers/base.py init_process:128 
      <-  site-packages/gunicorn/arbiter.py spawn_worker:517 
      <-  site-packages/gunicorn/arbiter.py spawn_workers:549 
      <-  site-packages/gunicorn/arbiter.py manage_workers:484 
      <-  site-packages/gunicorn/arbiter.py run:179 
      <-  gunicorn/app/base.py run:72 
      <-  gunicorn/app/base.py run:192 
      <-  gunicorn/app/wsgiapp.py run:74 
      <-  venv/bin/gunicorn <module>:11
```

So this means that of an observed second 30% of the wall clock time of a whole web app worker process were spent in `gunicorn/workers/workertmp.py -> notify:43  -> os.fchmod(self._tmp.fileno(), self.spinner)` (and it is the hottest stack sample). The similar behavior is observed for all other workers which also run at the same time.
I would like to understand what does this part of gunicorn do and if there is an "easy" way to optimize it somehow?

We run on AWS on some large instance, Ubuntu, gunicorn==19.5.0, gunicorn is set up the following way: 4 copies of gunicorn, each has workers = 4, preload_app = true, all this behind nginx, which load balances evenly between them. Under load all CPU cores are utilized to 100% (this is mainly user cpu time of our app code).

**Comment by fillest** [comment] 2016-07-07 17:23
Oh, looks like it happens when the main disk is full (it currently gets full periodically due to nginx log spam). Our /tmp/ is on / (not memfs), maybe it could be related

**Comment by tilgovi** [comment] 2016-07-13 20:23
Oh, looks like it happens when the main disk is full (it currently gets full periodically due to nginx log spam). Our /tmp/ is on / (not memfs), maybe it could be related

Does this mean that your problem is solved, @fillest?

**Comment by fillest** [comment] 2016-07-26 10:34
Well, right now I've caught it comsuming e.g. ~2-3% of a wall-clock second on each process under even ~700rps load. Which is a bit weird because app server should not touch the file systemat all by itself during request handling (if we need good performance). At least, I would like to get some understanding - for what exactly this file is used? Could it be set up once without calling fchmod or fchmod is somehow used for triggering notifications?

Also I currently would like not to touch /tmp/ for now, can I configure gunicorn to use a different path for these files? Is it configured by `worker_tmp_dir`?

**Comment by benoitc** [comment] 2016-07-27 07:45
worker_tmp_dir is for it. 

Right now this is the way the arbiter knows the worker are alive. It's strange it fill your disk, neither it i uses so much wall-clock. I simply don't reproduce it there. What is the filesystem? What are the mount options?

**Comment by fillest** [comment] 2016-08-02 15:51
Whoah, just got half a minute full iowait on the main disk and all gunicorns 100% of time waiting in fchmod. In theory that could be caused by some EBS-reladed lags. We are on AWS and the root volume is EBS-backed and EBS is roughly speaking a network attached storage.
Nothing new - just FYI.
But probably worth mentioning in the docs that worker_tmp_dir should be put in memory for improved stability and performance.
I've also already made a tmpfs mount but we haven't deployed the changes to the production yet.

**Comment by benoitc** [comment] 2016-08-08 16:19
@fillest the tmpfile will disapear in a coming a version. More about it soon. Waiting it happen i will let the ticket open.

**Comment by benoitc** [comment] 2016-08-08 16:20
in the mean time we could probably document it. @fillest do you mind to send us a PR?

**Comment by fillest** [comment] 2016-08-09 12:51
>tmpfile will disapear
Good news, thanks!
What changes are you planning? Just an idea - probably os.pipe would be a good option to use with forking as looks like it's the fastest for IPC (comparing to sockets-like methods) and is still not complex to use (comparing to shared memory).

>in the mean time we could probably document it. @fillest do you mind to send us a PR?
Can't promise but I will try

**Comment by fillest** [comment] 2016-08-12 00:53
An attempt for the docs: #1329 
I'm not sure if I edited the right file though or if markup is fully correct - I'm completely unfamiliar with docs generation, please help me with it.

**Comment by tilgovi** [comment] 2018-04-28 01:43
Now that it's documented to avoid having worker temporary files on disk, I'm going to close this in favor of #1760.

**Closed by tilgovi** 2018-04-28 01:43 UTC
Labels: - Mailing List -, Documentation, Feature/IPC, Improvement

**Comment by danigosa** [comment] 2019-05-30 19:24
@tilgovi it worths noting that the documented solution _does not work_ for docker if you are mounting as a volume. But it has a ridiculous fix, adding this parameter to `docker run`:

```
--tmpfs /tmp:rw,size=102400k,mode=1777 
```

If anyone using `minikube` or having issues in Kubernetes, you can also mount a tmpfs: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
