### ISSUE TITLE
Incompatibility with WSGI servers while using transfer-encoding: chunked

### ISSUE THREAD

**Issue by rishabh-bector** [benoitc/gunicorn#1803] opened 2018-06-07 20:14 UTC
I have an extremely simple Flask server running with Gunicorn and WSGI, which I'd like to send POST requests to. I need these requests to use chunked transfer encoding, with some form data sent as part of the request. However, when I send a POST to my gunicorn server, the request data received by the flask app is empty. If I switch the transfer encoding to anything else, it works properly.

Steps to reproduce:

- Create a simple python server in Flask:
```
from flask import Flask, jsonify, request
app = Flask(__name__)

@app.route('/', methods=['POST'])
def hello_world():
    print(request.form)
    return "Hello, World!"

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
```

- Create a WSGI entry and run it with Gunicorn
```
from server import app as application

if __name__ == '__main__':
    application.run()
```
`bash~: gunicorn --bind 0.0.0.0:8000 --log-level debug wsgi`

- Send a POST request to the Gunicorn server with chunked transfer encoding and some data (I was using POSTMAN)

**Request Headers:**
content-type:"multipart/form-data; boundary=--------------------------306493959385924197334276"
transfer-encoding:"chunked"
cache-control:"no-cache"
accept:"*/*"
host:"localhost:8000"
accept-encoding:"gzip, deflate"
content-length:163

**Request Body:**
test:"true"

- Observe the printed form data on the gunicorn output. Then send the same request with a different transfer encoding (gzip/deflate). The form data will only go through and be visible if the transfer encoding is NOT chunked.

**Gunicorn Output (chunked encoding)**
`ImmutableMultiDict([])`

**Gunicorn Output (gzip encoding)**
`ImmutableMultiDict([('test', 'true')])`

I'm not really sure what is causing this. It might have something to do with the `content-length` header. I would really appreciate it if you can get back as soon as possible!

**Comment by rishabh-bector** [comment] 2018-06-25 18:45
Is there any status on this?

**Comment by tilgovi** [comment] 2018-06-25 19:14
I'm happy to take a look but have limited time to do so this week. If you can share a gist or a repo with a script to reproduce the error that would help!

**Comment by teuneboon** [comment] 2018-06-27 10:38
We seem to have similar issues when running gunicorn 19.8.1 with WSGI Django behind an Apache load balancer which does gzip encoding(which in Apache means it does a chunked transfer as well). 

However: when we make requests directly to the gunicorn server, even if we DON'T use chunked encoding we seem to get SSL errors(haven't tested with SSL disabled yet, possibly that makes it clearer what's going wrong). The non-chunked errors are only reproducible if we send multiple requests at once:

    for i in `seq 1 10`; do curl 'https://<url here>' -H 'User-Agent: test' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'a=b' &; done

So maybe this is related?

Downgrading to 19.7.1 seems to fix these issues in some limited testing, we downgraded to 19.6.0 however because that's what we were using before we got these issues. So maybe you can try that for now @rishabh-bector ?

**Comment by rishabh-bector** [comment] 2018-06-27 16:57
Sure: https://github.com/rishabh-bector/Gunicorn1803

Just follow the instructions in the readme to reproduce.

**Comment by rishabh-bector** [comment] 2018-06-27 17:13
@teuneboon  I tried downgrading, unfortunately that didn't help.

**Comment by rishabh-bector** [comment] 2018-06-28 15:42
@benoitc I'm running Flask version 1.0.2

**Comment by marnovdm** [comment] 2018-06-29 06:52
@rishabh-bector; we had to downgrade eventlet to 0.20.1. Gunicorn 19.6.0 does not yet support eventlet >=0.21. Perhaps that's the case for you as well?

**Comment by rishabh-bector** [comment] 2018-06-29 14:12
@marnovdm Just tried that, unfortunately did not work.

**Comment by dumblob** [comment] 2018-09-19 14:12
@benoitc could you please post the untested/unfinished code somewhere? I would need a solution quite quickly and therefore would like to help somehow if you won't mind.

**Comment by benoitc** [comment] 2019-01-24 15:31
#1969 fix it but in any case you should make sure your client doesn't end both headers. This will work but it's not a good practice. Closing the issue then.

**Closed by benoitc** 2019-01-24 15:31 UTC
