### ISSUE TITLE
the worker was restart during the woker is running

### ISSUE THREAD

**Issue by sirpqp** [benoitc/gunicorn#3142] opened 2024-01-30 09:31 UTC
when the configration :max_requests=1000 and max_requests_jitter=100 was defined，
at some time the log show：[2024-01-30 15:22:06 +0800] [101428] [INFO] Autorestarting worker after current request.

But the worker was restarted during the woker is running!
i hope the worker never autorestart or  the autorestart time without the worker is runing!
how can i solve it?

**Comment by zogzog** [comment] 2024-02-08 09:21
This looks like a dupe of https://github.com/benoitc/gunicorn/issues/3038 (which is a real concern by the way, "merely assisting" in mitigating unfixable mem leaks is a worthwhile feature).

**Comment by benoitc** [comment] 2024-08-06 16:45
no activity since awhile. closing feel free to create a new ticket if needed.

**Closed by benoitc** 2024-08-06 16:45 UTC
