### ISSUE TITLE
Is there a way to specify WSGI app in the config file?

### ISSUE THREAD

**Issue by Mr-indescribable** [benoitc/gunicorn#1758] opened 2018-04-26 08:54 UTC
Hi,

I'm trying to specify the WSGI app in my Gunicorn config file. But I don't find any information about WSGI app configuration in the [settings documentation](http://docs.gunicorn.org/en/stable/settings.html).

So, is there any way to specify the WSGI app in the config file? Just like what uWSGI supported:

```
module=module_conains_the_app
callable=app
```

-----------------------

And yes, of course I know I can do it with the command line:

```
gunicorn -c <config-file> module:app
```

**Comment by berkerpeksag** [comment] 2018-04-26 12:08
This is not possible to do at the moment but there is an open issue (#1359) and PR (#1450)

Closing this as a duplicate of #1359.

**Closed by berkerpeksag** 2018-04-26 12:08 UTC

**Comment by Mr-indescribable** [comment] 2018-04-27 05:03
:pensive:  Well, thank for answering.
