### ISSUE TITLE
Regression in reloader behavior after a syntax error

### ISSUE THREAD

**Issue by tilgovi** [benoitc/gunicorn#2248] opened 2020-01-25 00:01 UTC
According to a [comment](https://github.com/benoitc/gunicorn/issues/2133#issuecomment-573362898) on #2133, a regression in the reloader, introduced in 3054b18, breaks reloading when files have syntax errors.

**Comment by LiquidLemon** [comment] 2020-01-26 15:11
I noticed this a few days ago, see #2244.

**Comment by berkerpeksag** [comment] 2020-01-26 16:17
Thank you for your detailed report, @LiquidLemon. I'm closing this one as a duplicate of #2244. In https://github.com/benoitc/gunicorn/issues/2133#issuecomment-578484384 @trendels said that there is an almost ready patch to fix the regression.

**Closed by berkerpeksag** 2020-01-26 16:17 UTC
