### ISSUE TITLE
Getting sometimes "The requested URL was not found on this server"

### ISSUE THREAD

**Issue by komaldedhia** [benoitc/gunicorn#1604] opened 2017-09-20 22:00 UTC
Hi,

I am running flask on Gunicorn server. I start server using following command:-
gunicorn getTerms:app -p $pidFile -b 0.0.0.0:4080 -D  --error-logfile $serverLogFile --access-logfile $serverLogFile --workers 4 --threads 2 --worker-class gevent --keep-alive 5 --timeout 30 --worker-connections 1000

and sometimes I get "The requested URL was not found on this server" error.
Any help is appreciated.

Thanks,
Komal.

**Comment by tilgovi** [comment] 2017-09-21 15:47
Can you say anything more about when this happens? Are you requesting a route that your flask app does not define? That sounds like a regular 404 error, not a gunicorn error.

**Comment by tilgovi** [comment] 2017-09-21 15:48
Is it possible your application is making an external web request and getting a 404 from that external site? Maybe that's throwing an exception that Flask then returns to Gunicorn and it ends up rendering that response.

**Comment by komaldedhia** [comment] 2017-09-21 17:58
It sometimes comes and sometimes doesn't.

**Comment by tilgovi** [comment] 2017-09-21 21:02
I'm sorry, but you will need to provide code that reproduces this or some more information about your deployment and what requests cause this, or maybe some information about what your application does.

Does it happen on any requests, or only some routes?

Does the client get a 404, like I said?

**Comment by tilgovi** [comment] 2017-09-21 21:04
Also, I noticed an unrelated issue with the way you're running Gunicorn. The threads switch sets the `gthread` worker and overrides `--worker-class gevent`. You cannot use gevent and threads at the same time.

**Comment by komaldedhia** [comment] 2017-09-21 22:53
Yes, the Client gets 404 randomly. For the same request, it sometimes gets
the response and sometimes doesn't get the response. I would not be in the
position to provide the code.
The code is very simple. I am using Flask framework. When a request comes,
it reads data from SQLite DB and renders JSON response back.

**Comment by tilgovi** [comment] 2017-09-21 23:13
If you cannot provide code to reproduce I don't think I can help. Gunicorn does not do request routing, it just passes the WSGI environment to Flask. Gunicorn doesn't return 404, Flask does. I'm not aware of any issues ever being reported with Gunicorn parsing inconsistently.

**Comment by komaldedhia** [comment] 2017-09-22 01:39
So I had shut down Gunicorn server for say around 15 mins and after
starting the server back, my API ran smoothly with no intermittent 404.
Also, when I was checking logs of Gunicorn, I could not even see the
request (for which I was getting 404) printing in the logs. Wonder if this
could be the issue of the flask.

Thanks for the help Randall :)

**Comment by tilgovi** [comment] 2017-09-22 03:05
I wonder if this is due to the new SO_REUSEPORT option. We have an open issue to make it optional, because it is sometimes confusing. Perhaps you had an older copy of Gunicorn running also, and the two copies were alternating serving requests. Maybe an old version didn't have the latest code.

Is it okay to close the issue?

**Comment by komaldedhia** [comment] 2017-09-22 17:41
I haven't change the Gunicorn version. I have 19.7.0 running on. Am I
supposed to change any configuration and which version has this issue fixed?

**Comment by tilgovi** [comment] 2017-09-22 20:22
The change I was referring to is not commit yet.

I meant that maybe you had two versions of *your* code, one without a route defined and sometimes that was giving a 404.

For the moment, just be sure that you restart Gunicorn if you change your code and you should be fine.

**Comment by CodeSpent** [comment] 2018-11-29 05:09
I'm not sure if this is related to your issue, but I'd mention it since the symptoms were similar to my issue.

https://stackoverflow.com/questions/33241050/trailing-slash-triggers-404-in-flask-path-rule/33285603#33285603

Sometimes the browser will interpret the route with a / at the end, or without. So if a user accidentally puts an extra /, it doesn't match the route. So make sure your routes are defined as /route/ to handle both scenarios.

**Comment by CodeSpent** [comment] 2018-12-11 02:48
Well, I can now attest that the above solution did not resolve the issue, and I can see why OP is unable to explain anything, because we're really not given much. If I were to create a single route application for the root route, navigating to it from flask is fine. Get Gunicorn in the mess and only about 60% of the time it'll go to the route, other times it just says "Not Found". I don't know how to make Gunicorn verbose enough to give you any details, but its definitely an issue with Gunicorn as this test was on a route with a single string return.

**Comment by j0nimost** [comment] 2019-01-17 17:23
I have a deadline tomorrow and my flask app just spit out this error and I can't solve it

**Comment by benoitc** [comment] 2019-01-17 17:32
@j0nimost same question than the one given to @CodeSpent , do you have any test that could help to reproduce the issue? Any log? What Url get your flask. Which route did you set? How? 

something like the example
https://github.com/benoitc/gunicorn/blob/master/examples/frameworks/flaskapp.py 

with the route that fail would help. Btw what version of flask are you using and how are you launching gunicorn? Can you provide the command line and if you use it the ocnfiguration of the proxy on top?

**Closed** 2023-05-07 17:55 UTC
Labels: Feedback Requested, unconfirmed

**Comment by WilliamChen-luckbob** [comment] 2024-03-12 01:57
> @j0nimost same question than the one given to @CodeSpent , do you have any test that could help to reproduce the issue? Any log? What Url get your flask. Which route did you set? How?
> 
> something like the example https://github.com/benoitc/gunicorn/blob/master/examples/frameworks/flaskapp.py
> 
> with the route that fail would help. Btw what version of flask are you using and how are you launching gunicorn? Can you provide the command line and if you use it the ocnfiguration of the proxy on top?

I have the same issue when using `gunicorn==20.1.0`. A reproduce issue is quite hard to give, this situation comes up when numbers of apis going up, now I have up to 100 apis seperated in 10+ namespaces, the flask application then get 404 occasionally when requesting the exactly same api. I don't know if this is the problem that no one can gives a reproduce code.
