### ISSUE TITLE
Adding duplicate Requests for many concurrent requests

### ISSUE THREAD

**Issue by shreeraj04** [benoitc/gunicorn#2391] opened 2020-07-30 07:42 UTC
Gunicorn version: 20.0.4
Python version: 3.7.8
System specification: 4 core, 8 GB RAM, using 9 workers and --preload

I am sending 1000 requests in 1 second from Apache Jmeter. Each request is added to the DB. Upon completion of all requests when checked in DB it would have more than 1000 records (ex: around 1200 records). I observed the session ID and checked for distinct - it was exactly 1000. 
Hence, I think Gunicorn is duplicating some requests. I am using the below command:-

**gunicorn app:app --bind --worker-class=aiohttp.GunicornWebWorker --workers=9 --preload**

Is there any configuration to avoid duplication ?

Thanks in advance.

**Comment by iamajay** [comment] 2020-08-20 09:18
Did you find workaround or the fix for this as I am also having same issue.

**Comment by shreeraj04** [comment] 2020-08-21 05:03
No @iamajay I didn't find any workaround or fix for this. Gunicorn contributors have to help us here.
Also, if you get one please help to post it here. Thanks in advance!

**Comment by benoitc** [comment] 2020-08-21 05:20
There are no duplicate requests in gunicorn.we don't keep them in memory just process them ws soon ws they come. Unless the qiohttp worker is buggy which
s not maintained by gunicorn authors.

Do you haave any example of code and logs that could help us to reproduce the issue?

**Comment by iamajay** [comment] 2020-08-21 06:04
@benoitc, I would have thought same so I have started using gevent worker class since in case qiohttp is buggy and I can see same issue here as well, for my single request I can see the logs for a single function call twice. It is hard to reproduce and trace the issue by applying breakpoints as it occurs once or twice in a thousand request, I found this behavior while looking logs for some other purpose. I can give an example of what my code and logs look like and the logs when issue occurs.

gynicorn_conf.py
`
import multiprocessing

worker_class = "gevent"
bind = "0.0.0.0:5000"
workers = multiprocessing.cpu_count() * 2 + 1
timeout = 3 * 60  # 3 minutes
keepalive = 24 * 60 * 60  # 1 day
capture_output = False
`

wsgi.py
`
from app import app

`

app.py
`
from flask import Flask, request, abort, jsonify
from until import do_something
import uuid

app = Flask(__name__)


@app.route('/test', methods=['POST'])
def get_square():
    request_id = uuid.uuid4().hex
    do_something(request_id)
    return jsonify({'request_id': request_id})

`
until.py
`
import logging
import requests

logging.basicConfig(level=logging.DEBUG)


def do_something(request_id):
	r = requests.get("https://google.com")
	logging.debug(f"request_id:{request_id}, status_code:{r.status_code}")
	return True
`

**gunicorn -c gunicorn_conf.py wsgi:app**

app.log
`
2020-08-20 21:26:45.055 | DEBUG | get | 1341 | request_id:6f87f0f7a71249918470c27f30168ac2, status_code:200
2020-08-20 21:26:45.055 | DEBUG | get | 1341 | request_id:6f87f0f7a71249918470c27f30168ac2, status_code:200

`

**Comment by iamajay** [comment] 2020-10-15 09:37
@benoitc from more debugging I can see that one single request was passed to two different workers simultaneously in case of gevent worker type. Any thoughts or suggestions to avoid this?

**Comment by 50Bytes-dev** [comment] 2020-12-08 20:08
same problem. how to fix it? so far I am using redis to protect against duplicates, it is not convenient

**Comment by shreeraj04** [comment] 2020-12-10 04:30
I have also eliminated Gunicorn due to this reason now. Cannot afford to have duplicates. 

I have implemented Kubernetes cluster for the huge request load. It works like a charm. Until and unless this issue in Gunicorn is identified and fixed we cannot use this for huge concurrent requests.

**Comment by 50Bytes-dev** [comment] 2020-12-10 19:17
> I have also eliminated Gunicorn due to this reason now. Cannot afford to have duplicates.
> 
> I have implemented Kubernetes cluster for the huge request load. It works like a charm. Until and unless this issue in Gunicorn is identified and fixed we cannot use this for huge concurrent requests.

Please tell us in more detail what you used

**Closed** 2022-10-14 09:11 UTC
