### ISSUE TITLE
Documentation on --threads together with --workers

### ISSUE THREAD

**Issue by heyman** [benoitc/gunicorn#1364] opened 2016-10-10 12:42 UTC
Hi & thanks for a really great project!

I'm trying to understand how `--threads` works together with `--workers`. The documentation states the following on `--threads`:

```
Run each worker with the specified number of threads.
```

To me that sounds like a server running with `-w 8 --threads=4` should be able to handle ~32 requests concurrently, as long as what's done in the requests are I/O. However, I did a small test to try this out where I had a web endpoint that simply did `time.sleep(1.0)` and when I ran Apache Bench with the parameters `-c 32 -n 320` (do 320 requests with 32 running concurrently) against this endpoint it didn't take slightly more than 10 seconds as I would have expected. Instead it took ~20 seconds (as if only 16 requests were being processed concurrently).  If I instead run the server with `-w 8 --threads=8`, it only takes ~10 seconds to complete the 320 requests. 

I'm trying to understand the reason for this. Have I completely misunderstood how `--threads` work together with `--workers`?

EDIT: I ran the tests on OSX.

**Comment by thefab** [comment] 2016-10-11 07:22
+1

**Comment by berkerpeksag** [comment] 2016-10-12 17:24
Did you use the sync worker? I've never used the threads option so far, but quoting from http://docs.gunicorn.org/en/stable/design.html#how-many-threads:

> Using threads assumes use of the sync worker.

In any case, we should clarify the documentation. Thanks for the report.

**Comment by heyman** [comment] 2016-10-12 17:32
Well, when starting gunicorn with `--threads` specified (even when you explicitly set `--worker-class=sync`) it always logs the following:

```
[2016-10-12 19:30:09 +0200] [40476] [INFO] Using worker: threads
```

**Comment by benoitc** [comment] 2016-10-16 16:14
can you share the application you have to test it?

**Comment by heyman** [comment] 2016-10-17 08:35
@benoitc: Here's a small Flask app that can be used to test it:

```python
import time

from flask import Flask
app = Flask(__name__)

@app.route("/wait")
def wait():
    time.sleep(1.0)
    return "ok"
```

Gunicorn command:

`gunicorn -b 127.0.0.1:8080 -w 8 --threads=4 gunicorn_test:app`

And the ab command:

`ab -n 320 -c 32 http://127.0.0.1:8080/wait`

**Comment by decaz** [comment] 2018-02-20 16:45
Any news or updates here?

**Comment by tilgovi** [comment] 2018-02-20 19:11
Threads do not work together with workers. `--threads` implies `--worker-class gthread`. It maybe the case that `--threads` takes precedence. To be honest, I don't know. We have other open issues where people have expressed confusion. If anyone wants to update the documentation, please open a pull request and I will be happy to help review the language and the content.

For now, I'll close this issue, because I think the original question has been answered.

**Closed by tilgovi** 2018-02-20 19:11 UTC
Labels: - Mailing List -, Documentation

**Comment by quantus** [comment] 2018-09-20 20:13
I'd like to use multiple worker processes for performance reason, and threads within those worker processes. I want to use threads to mitigate the issue where a single slow request is blocking other request that are queued to the same process.

I happened to find this page, and found @tilgovi's answer "Threads do not work together with workers." a bit puzzling, as I don't see any obvious reasons why those two couldn't be used together. So I started running small tests to confirm that everything works, and while doing that I managed to find out the reason to the slowess @heyman experienced in this first message.

The issue is that the requests are not being distributed to the workers evenly, and therefore we don't get the full performance out of the workers and processes. As to my understanding the OS kernel is responsible for distributing the requests to the workers, but there is no fairness guarantees to how many requests each worker receives.

How I figured this out:

gunicorn_test.py
```python
import time, os, threading

from flask import Flask
app = Flask(__name__)

app.requests = []

@app.route("/wait")
def wait():
    time.sleep(1.0)
    app.requests.append(f'pid: {os.getpid()} tid: {threading.currentThread().name}\n')
    return f'pid: {os.getpid()} tid: {threading.currentThread().name}\n'
```

gunicorn_test_conf.py:
```python
import os


def worker_exit(server, worker):
    print(f'Worker pid:{os.getpid()} served {len(worker.app.callable.requests)} requests')

```

Execution:
```
$ gunicorn -b 127.0.0.1:8080 -w 8 --threads=4 gunicorn_test:app --config=gunicorn_test_conf.py
[2018-09-20 22:38:37 +0300] [94208] [INFO] Starting gunicorn 19.9.0
[2018-09-20 22:38:37 +0300] [94208] [INFO] Listening at: http://127.0.0.1:8080 (94208)
[2018-09-20 22:38:37 +0300] [94208] [INFO] Using worker: threads
[2018-09-20 22:38:37 +0300] [94211] [INFO] Booting worker with pid: 94211
[2018-09-20 22:38:37 +0300] [94212] [INFO] Booting worker with pid: 94212
[2018-09-20 22:38:37 +0300] [94213] [INFO] Booting worker with pid: 94213
[2018-09-20 22:38:37 +0300] [94214] [INFO] Booting worker with pid: 94214
[2018-09-20 22:38:37 +0300] [94215] [INFO] Booting worker with pid: 94215
[2018-09-20 22:38:37 +0300] [94216] [INFO] Booting worker with pid: 94216
[2018-09-20 22:38:37 +0300] [94217] [INFO] Booting worker with pid: 94217
[2018-09-20 22:38:37 +0300] [94218] [INFO] Booting worker with pid: 94218
^C[2018-09-20 22:39:11 +0300] [94208] [INFO] Handling signal: int
[2018-09-20 22:39:11 +0300] [94216] [INFO] Worker exiting (pid: 94216)
[2018-09-20 22:39:11 +0300] [94212] [INFO] Worker exiting (pid: 94212)
Worker pid:94212 served 16 requests
Worker pid:94216 served 68 requests
[2018-09-20 22:39:11 +0300] [94217] [INFO] Worker exiting (pid: 94217)
[2018-09-20 22:39:11 +0300] [94215] [INFO] Worker exiting (pid: 94215)
Worker pid:94215 served 55 requests
Worker pid:94217 served 67 requests
[2018-09-20 22:39:11 +0300] [94211] [INFO] Worker exiting (pid: 94211)
Worker pid:94211 served 3 requests
[2018-09-20 22:39:11 +0300] [94214] [INFO] Worker exiting (pid: 94214)
[2018-09-20 22:39:11 +0300] [94213] [INFO] Worker exiting (pid: 94213)
[2018-09-20 22:39:11 +0300] [94218] [INFO] Worker exiting (pid: 94218)
Worker pid:94214 served 24 requests
Worker pid:94218 served 72 requests
Worker pid:94213 served 15 requests
[2018-09-20 22:39:11 +0300] [94208] [INFO] Shutting down: Master
```

To get the 32 req/s @hayman originally expected, every worker would need to handle 40 requests. In this case the slowest one handled 72 request and caused the extra delay.

Other console:
```
$ ab -n 320 -c 32 http://127.0.0.1:8080/wait
...
Requests per second:    16.73 [#/sec] (mean)
...
```

I still need to test this a bit more before I'll start using this in my production applications, but so far I haven't seen any problems.

**Comment by tilgovi** [comment] 2018-09-20 20:53
Updated my comment to say "threads do not work with worker _classes_". All I meant was that the threaded worker _is a_ worker type. So `--threads 5 --worker-class gevent` doesn't make sense because `--threads` implies `--worker-class gthread`.

**Comment by tilgovi** [comment] 2018-09-20 20:53
You might try `--reuse-port` to see if it helps with the process balancing.

**Comment by quantus** [comment] 2018-09-21 09:36
Thanks for the clarification! Now understand what you meant.

I tested adding the `--reuse-port` argument but it didn't have any effect to the results. I don't personally see uneven request balancing as an issue as I should be able to use the threads to avoid the unnecessary waiting behind slow request.
