### ISSUE TITLE
LookupError: unknown encoding: hex_codec(run code in not root user)

### ISSUE THREAD

**Issue by iChost** [benoitc/gunicorn#2358] opened 2020-06-12 09:19 UTC
The detail description 
[LookupError: unknown encoding: hex_codec(run code in not root user)
](https://stackoverflow.com/questions/62337289/lookuperror-unknown-encoding-hex-codecrun-code-in-not-root-user)

The code in a flask project
```
import codecs
c = codecs.encode(b"sdf", "hex_codec")
print(c)
```

use `nginx+supervisord+gunicorn` to run this project, has the exception

[2020-06-12 15:36:32,342] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/www/wwwroot/demo/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/www/wwwroot/demo/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/www/wwwroot/demo/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/www/wwwroot/demo/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/www/wwwroot/demo/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/wwwroot/demo/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/demo/app.py", line 9, in hello_world
    c = codecs.encode(b"sdf", "hex_codec")
LookupError: unknown encoding: hex_codec
[2020-06-12 15:36:32 +0800] [10100] [DEBUG] Closing connection.

```
run in “root”, works ok! run in “www”, has the exception.

**Comment by jamadden** [comment] 2020-06-12 10:32
This is just a guess, but most likely the problem is some sort of error with your Python installation. According to the stackoverflow post, you're taking a virtual environment created by one user (root) and then attempting to use it as another user, and you've had problems like this, and the standard library `import json` failing. 

I suggest removing the virtual environment and creating it as the user you intend to use it as. (I'm suspicious of permission problems or faulty symlinks. Again, this is just a guess.)

**Comment by benoitc** [comment] 2020-07-09 13:14
no answer from the requester since awhile. closing the issue.

**Closed by benoitc** 2020-07-09 13:14 UTC
