### ISSUE TITLE
Gunicorn runs and causes this error please help

### ISSUE THREAD

**Issue by alfonsomarineparts** [benoitc/gunicorn#1982] opened 2019-02-07 00:48 UTC
# 504-Gateway-Time-out-nginx-1.10.3-Ubuntu-
504 Gateway Time-out nginx/1.10.3 (Ubuntu) On the Putty console gunicorn runs and causes this error please help

**Comment by benoitc** [comment] 2019-02-07 05:34
can you provide more information to reproduce this etror? any log files from  gunicorn? how do you launch it? what does your application?

**Comment by javabrett** [comment] 2019-02-22 03:25
ping @alfonsomarineparts

**Comment by benoitc** [comment] 2019-11-23 00:09
closing the issue since no feedback given. thanks.

**Closed by benoitc** 2019-11-23 00:09 UTC
Labels: Feedback Requested
