### ISSUE TITLE
apache + gunicorn gives internal server errors upon code change

### ISSUE THREAD

**Issue by VidJa** [benoitc/gunicorn#2017] opened 2019-04-19 13:20 UTC
I'm using apache as proxy in front of our pre-production machine. Upon code change I am seeing internal server error 500. They disappear after a few refreshes after which the site is stable
This happens every time when I do a git pull on the site's codebase and restart gunicorn
Any ideas how to prevent this?

## Proxy rules
  ProxyRequests Off
  ProxyPreserveHost Off
  ProxyPass /static !
  ProxyPassReverse /static !
  ProxyPass /media !
  ProxyPassReverse /media !
  ProxyPass / http://127.0.0.1:8000/ retry=0
  ProxyPassReverse / http://127.0.0.1:8000/

#### gunicorn settings
"--reload --graceful-timeout 600 --timeout 600 --workers 3 --bind 0.0.0.0:8000 wsgi:application"

**Comment by berkerpeksag** [comment] 2019-04-19 13:30
IMO, this is an expected behavior since you passed the `--reload` option. You can see the same behavior in your local environment especially if you have a big application (it takes time to reload an application) I think sending a `HUP` signal to Gunicorn's master process would be a more reliable option: https://docs.gunicorn.org/en/stable/signals.html#master-process

**Comment by benoitc** [comment] 2019-04-29 12:04
or using USR2 but yes.

**Comment by benoitc** [comment] 2019-05-23 20:54
closing the issue as answered.

**Closed by benoitc** 2019-05-23 20:54 UTC
