### ISSUE TITLE
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

### ISSUE THREAD

**Issue by UpolRys** [benoitc/gunicorn#1119] opened 2015-09-28 13:54 UTC
Hello there,
I am facigin with very strange error when using gunicorn. the saame app code that now I having this error message  
[2015-09-28 16:46:52 +0000] [6027] [INFO] Starting gunicorn 19.3.0
[2015-09-28 16:46:52 +0000] [6027] [INFO] Listening at: http://127.0.0.1:8000 (6027)
[2015-09-28 16:46:52 +0000] [6027] [INFO] Using worker: sync
[2015-09-28 16:46:52 +0000] [6032] [INFO] Booting worker with pid: 6032
[2015-09-28 16:46:52 +0000] [6032] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named w
Traceback (most recent call last):
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named w
[2015-09-28 16:46:52 +0000] [6032] [INFO] Worker exiting (pid: 6032)
Traceback (most recent call last):
  File "../bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 174, in run
    self.manage_workers()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/home/orubadell/falconTutorial/environments/tutorial/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

was compiled successfully and I was able to get the output from the localhost. But now it is giving me this error. I tried following solution [ gunicorn app:application -b localhost:3000 ] that was stated in this thread https://github.com/benoitc/gunicorn/issues/338. I was able to try just this one since I am not ursing django ,, i am using falcon as my web framework.

**Comment by tilgovi** [comment] 2015-10-01 19:16
I see `ImportError: No module named w`. Is `w` the name of your application package? Have you installed your application correctly so that it's importable by gunicorn? Or are you launching gunicorn by pointing it directly at the `.py` file?

Can you show the full gunicorn command you use? Have you run other gunicorn applications successfully? Can you run your application with wsgiref or any other WSGI server?

**Comment by benoitc** [comment] 2015-11-14 11:33
bump. doesn't look like a gunicorn error. Can you confirm?

**Comment by extremewaysback** [comment] 2015-12-06 11:04
I got the same error. Find out that the root cause is an application which can't be installed through gunicorn. After disabling the related application in setting.py module, it works!

**Comment by extremewaysback** [comment] 2015-12-06 11:04
I got the same error. Find out that the root cause is an application which can't be installed through gunicorn. After disabling the related application in setting.py module, it works!

**Comment by extremewaysback** [comment] 2015-12-06 11:04
I got the same error. Find out that the root cause is an application which can't be installed through gunicorn. After disabling the related application in setting.py module, it works!

**Comment by extremewaysback** [comment] 2015-12-06 11:04
I got the same error. Find out that the root cause is an application which can't be installed through gunicorn. After disabling the related application in setting.py module, it works!

**Comment by benoitc** [comment] 2015-12-06 14:43
> an application which can't be installed through gunicorn

what do you mean by can't be installed? Did you set the python path correctly?

**Comment by extremewaysback** [comment] 2015-12-06 15:10
It’s just a application I was testing something with, not complete. Forget to disable the application in INSTALLED_APPS of settings.py, so get the gunicorn errors I think. So after correcting this error, I deploy my app successfully.

**Comment by benoitc** [comment] 2015-12-06 15:12
@extremewaysback ok, thanks!

closing the issue. no news since a while anyway...

**Closed by benoitc** 2015-12-06 15:12 UTC
Labels: Feedback Requested
