### ISSUE TITLE
ValueError: Invalid file descriptor: -1 when upgrading from 20.1.0 to 21.0.1

### ISSUE THREAD

**Issue by omgMath** [benoitc/gunicorn#3026] opened 2023-07-18 09:30 UTC
Hi there

We've upgraded to from version 20.1.0 to version 21.0.1 and we started to get the following error:

`ValueError: Invalid file descriptor: -1`

Stack trace is the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 232, in run
    self.murder_keepalived()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 176, in murder_keepalived
    self.poller.unregister(conn.sock)
  File "/usr/local/lib/python3.11/selectors.py", line 366, in unregister
    key = super().unregister(fileobj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/selectors.py", line 249, in unregister
 key = self._fd_to_key.pop(self._fileobj_lookup(fileobj))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
```

As I read the [changelog](https://docs.gunicorn.org/en/latest/2023-news.html) the release was only major to start the new release cycle, so I would not expect something to break? Am I missing something?

For completeness, our `gunicorn.conf.py`:

```
# general gunicorn settings
# https://docs.gunicorn.org/en/stable/settings.html

bind = "0.0.0.0:5000"
workers = 4

wsgi_app = "main:app"
threads = 8

# logging
accesslog = "-"

# The maximum number of requests a worker will process before restarting. 0 => disabled restarts
# Setting a value is recommended to avoid OOM
# https://docs.gunicorn.org/en/stable/settings.html#max-requests
max_requests = 100

# The jitter causes the restart per worker to be randomized by randint(0, max_requests_jitter)
# https://docs.gunicorn.org/en/stable/settings.html#max-requests-jitter
max_requests_jitter = 6

# Timeout for graceful workers restart.
# https://docs.gunicorn.org/en/stable/settings.html#graceful-timeout
graceful_timeout = 900  # high for restore and consistency checks

# defaults

# https://docs.gunicorn.org/en/stable/settings.html#timeout
timeout = 120  # Workers silent for more than this many seconds are killed and restarted.

logger_class = 'gunicorn_filtering_logger.CustomGunicornLogger'
```

We're using `python3.11` (which seems to be supported from 21.0.0).

Thanks for some feedback!

**Comment by alpden550** [comment] 2023-07-18 09:51
thanks, downgraded and fixed version as` gunicorn==20.1.0` 😅 works as usual

**Comment by benoitc** [comment] 2023-07-18 12:36
duplicate of #3029 fixed in latest master. Thanks for the report.

**Closed by benoitc** 2023-07-18 12:36 UTC

**Comment by benoitc** [comment] 2023-07-18 13:00
21.1.0 has been released with the fix https://github.com/benoitc/gunicorn/discussions/3031

**Comment by benoitc** [comment] 2023-07-18 13:01
21.1.0 has been released with the fix https://github.com/benoitc/gunicorn/discussions/3031 .
