### ISSUE TITLE
Gunicorn does not ignore Content-Length when Transfer-Encoding is set to chunked

### ISSUE THREAD

**Issue by komuW** [benoitc/gunicorn#1125] opened 2015-10-14 12:35 UTC
gunicorn version 19.2.1
Im running it as:
`gunicorn myApp.wsgi:application --workers=3 --bind="0.0.0.0:8000" --log-level debug --reload`

#request::
POST /mtn/zm/consumer/register HTTP/1.1
Host: some-Host
Accept: */*
Content-Type: text/xml; charset=UTF-8
User-Agent: Apache-HttpClient/4.2.3 (java 1.5)
Transfer-Encoding: chunked
Content-Length: -2054
Connection: close

The request hangs when I make that request. And I can see the request come in when I run tcpdump
`sudo tcpdump -i any -A -s 0 'tcp port 8000 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)'`

**Comment by benoitc** [comment] 2015-10-14 12:40
well Content-Length is always used in priotity, that's the common behavior. I will check if there is a rule for that.

**Comment by jamadden** [comment] 2015-10-14 12:43
There is a rule. I know because I recently dealt with something similar for gevent's pywsgi :)

From https://tools.ietf.org/html/rfc2616#section-4.4:

> If a Content-Length header field (Section 14.13) is present, its decimal value in OCTETs represents both the entity-length and the transfer-length. The Content-Length header field MUST NOT be sent if these two lengths are different (i.e., if a Transfer-Encoding header field is present). If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter MUST be ignored.

**Comment by komuW** [comment] 2015-10-14 12:52
@benoitc @jamadden ok. when I send a POST request with no Content-Length but with Transfer-encoding: chunked only; the request body doesnt make it to my app. ie my app sees an empty request body

#request::
POST /mtn/zm/consumer/register HTTP/1.1
Host: some-Host
Accept: /
Content-Type: text/xml; charset=UTF-8
User-Agent: Apache-HttpClient/4.2.3 (java 1.5)
Transfer-Encoding: chunked
Connection: close

**Comment by benoitc** [comment] 2015-10-14 13:07
@jamadden @komuW actually this is what we do in gunicorn "standard" workers:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/http/message.py#L110-L112

@komuW which worker are you using?

**Comment by komuW** [comment] 2015-10-14 13:17
@benoitc I'm using the default workers(sync)

**Comment by benoitc** [comment] 2015-10-14 13:22
@komuW so the error is somewhere else. any logs on gunicorn side?

**Comment by komuW** [comment] 2015-10-14 13:35
@benoitc there are no error logs as such, because <my_guess>since gunicorn is getting the request, its assuming the request is okay, it's just that the request body is empty</my_guess>

So in the gunicorn logs will log the request except that the request body is logged as empty

`[2015-10-14 13:32:03 +0000] [12556] [DEBUG] POST /my-url
2015-10-14 13:32:03,950 INFO module=views, process_id=12556, path=/some-django/views.py, environment=development, request_data=""`

Gunicorn is powering my django app and the logging is like:
`def post(self, request):
    logger.info(request_data=request.body)`

**Comment by benoitc** [comment] 2015-11-14 11:29
no other log line?

**Comment by benoitc** [comment] 2015-12-23 08:22
closing the issue. not reproduced.

**Closed by benoitc** 2015-12-23 08:22 UTC
Labels: Feedback Requested, Not confirmed

**Comment by pconesa** [comment] 2016-02-16 12:25
hi, it might not be a gunicorn thing but think I've got a similar situation and know how to reproduce it, not using gunicorn though, but might happens too. Actually it is happening in our production server (with unicorn) uploading a big file 100MB using wifi, but not ethernet (¿?).

Steps to reproduce:

1.- clone the minimal file upload repo from here: https://github.com/axelpale/minimal-django-file-upload-example.
2.- run it with  ip 0.0.0.0
3.- start up fiddler, may be something else that will reduce upload speed will work.
4.- in fiddler: click on Rules>Performance>Simulate modem speed
5.- Upload a big file (in my case it is a 100MB file)

There's no response from the server, fiddler shows -1.

Any ideas?
