### ISSUE TITLE
why use ascii instead of utf when coding the header?

### ISSUE THREAD

**Issue by Simplici** [benoitc/gunicorn#1625] opened 2017-10-17 09:18 UTC
"/usr/local/lib/python3.4/site-packages/gunicorn-19.7.0-py3.4.egg/gunicorn/http/wsgi.py",
line 338, in send_headers util.write(self.sock,util.to_bytestring(header_str, "ascii")) File

**Comment by jamadden** [comment] 2017-10-17 11:16
This looks like a duplicate of https://github.com/benoitc/gunicorn/issues/1353 (Long story short, headers are defined to be ASCII or Latin-1, not arbitrary Unicode.)

**Closed** 2017-10-17 17:56 UTC
