### ISSUE TITLE
Gunicorn hangs and stops responding abruptly when using gevent worker  inside docker conatiner

### ISSUE THREAD

**Issue by keshrisohit** [benoitc/gunicorn#1859] opened 2018-08-22 10:39 UTC
Gunicorn hangs and workers are unable to restart ,gunicorn config logs 
```
[2018-08-18 03:51:39 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9299)
[2018-08-18 03:51:39 +0000] [9299] [INFO] Worker exiting (pid: 9299)
[2018-08-18 03:51:40 +0000] [9347] [INFO] Booting worker with pid: 9347
[2018-08-18 03:51:41 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9305)
[2018-08-18 03:51:41 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9306)
[2018-08-18 03:51:41 +0000] [9305] [INFO] Worker exiting (pid: 9305)
[2018-08-18 03:51:41 +0000] [9306] [INFO] Worker exiting (pid: 9306)
[2018-08-18 03:51:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9317)
[2018-08-18 03:51:42 +0000] [9317] [INFO] Worker exiting (pid: 9317)
[2018-08-18 03:51:42 +0000] [9353] [INFO] Booting worker with pid: 9353
[2018-08-18 03:51:42 +0000] [1] [DEBUG] 2 workers
[2018-08-18 03:51:42 +0000] [9354] [INFO] Booting worker with pid: 9354
[2018-08-18 03:51:42 +0000] [9355] [INFO] Booting worker with pid: 9355
[2018-08-18 03:51:43 +0000] [1] [DEBUG] 4 workers
[2018-08-18 03:56:41 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9347)
[2018-08-18 03:56:41 +0000] [9347] [INFO] Worker exiting (pid: 9347)
[2018-08-18 03:56:42 +0000] [9394] [INFO] Booting worker with pid: 9394
[2018-08-18 03:56:43 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9353)
[2018-08-18 03:56:43 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9354)
[2018-08-18 03:56:43 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9355)
[2018-08-18 03:56:43 +0000] [9355] [INFO] Worker exiting (pid: 9355)
[2018-08-18 03:56:43 +0000] [9353] [INFO] Worker exiting (pid: 9353)
[2018-08-18 03:56:43 +0000] [9354] [INFO] Worker exiting (pid: 9354)
[2018-08-18 03:56:44 +0000] [9400] [INFO] Booting worker with pid: 9400
[2018-08-18 03:56:44 +0000] [1] [DEBUG] 2 workers
[2018-08-18 03:56:44 +0000] [9401] [INFO] Booting worker with pid: 9401
[2018-08-18 03:56:44 +0000] [9402] [INFO] Booting worker with pid: 9402
[2018-08-18 03:56:44 +0000] [1] [DEBUG] 4 workers
```

gunicorn config :

workers = 4
worker_class = 'gevent'
max_requests = 2400
max_requests_jitter = 20
timeout = 300
keepalive = 65
worker_connections = 1000

Aws machine config 
4 core    7.5 GiB   

versions:
pyhton  3.5.3
gunicorn 19.6.0
gevent 1.2.1
greenlet 0.4.13

Gunicorn logs

**Comment by thulasi-ram** [comment] 2018-08-24 08:04
More specifically it hangs in the `writev` system call.

**Comment by thulasi-ram** [comment] 2018-10-11 08:04
@benoitc Thanks for responding.

Currently, there is no way to reproduce it. It occurs randomly in production environment and were unable to reproduce in pre-production environments even when load tested.

As of now we suspect the python-alpine image we use for dockerization. The alpine image uses musl libc instead of glibc which provides the writev call.

From the official document at https://hub.docker.com/_/python/

> This variant is highly recommended when final image size being as small as possible is desired. The main caveat to note is that it does use musl libc instead of glibc and friends, so certain software might run into issues depending on the depth of their libc requirements. However, most software doesn't have an issue with this, so this variant is usually a very safe choice. See this Hacker News comment thread for more discussion of the issues that might arise and some pro/con comparisons of using Alpine-based images.

I think we should have treated this warning in a more critical way while choosing the docker image. Sorry to have got you included in this. Our knowledge and experience on how gevent interfaces with linux are very limited. We are moving to the official default(fat) image in a couple of weeks. Will keep you updated if we are facing this after that move.

In the meanwhile, it would be of great help if you can point us in a direction/to resources where we can extract more info as to what may be causing the exact issue. Let us know if you need the configuration / any other detail. Thanks in advance.

**Comment by justinmk2** [comment] 2019-04-09 14:09
@thulasi-ram does it happen with non-alpine image? I'm seeing similar behavior with `python:3.6` docker image.

**Comment by thulasi-ram** [comment] 2019-04-09 15:54
@justinmk2 Yes, it happens in non-alpine also but the behaviour is very random. With a few of my projects on 3.6/3.7, it does not happen. So I think some installed package and how it deals with I/O causes this.

**Comment by javabrett** [comment] 2019-12-25 05:39
@justinmk2 @thulasi-ram this is hard to diagnose without a reproducible Docker image and steps. Do you have a `Dockerfile` and steps or likely workloads to reproduce?

**Comment by thulasi-ram** [comment] 2020-01-12 17:53
Sorry, @javabrett . We weren't able to reproduce it either. The issue slowly faded away. My guess is it happens with a certain combination of packages. I am afraid thats all the info we have.

We can close this issue as **unable to reproduce / not enough info** as you deem fit.

**Comment by javabrett** [comment] 2020-01-12 21:30
Closing this for now as there is no clear path to reproduce this. Please open a new issue with a reproducible case should this reoccur.

**Closed by javabrett** 2020-01-12 21:30 UTC
Labels: Feedback Requested
